allowed_external_types = [
    "aws_sdk_s3::*",
    "aws_types::sdk_config::SdkConfig",
    "aws_smithy_runtime_api::*",
    "aws_smithy_types::*",
    "tokio::runtime::task::error::JoinError",
    "bytes::bytes::Bytes",
    "bytes::bytes::Buf",
]
