/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package software.amazon.s3tm.codegen

import java.nio.file.Files
import java.nio.file.Path
import java.util.logging.Level
import java.util.logging.Logger
import software.amazon.smithy.build.FileManifest
import software.amazon.smithy.model.node.Node

/** Assembles a standalone crate with the complete generated subtree at src/model. */
object ModelArtifact {
    fun assemble(
        generated: FileManifest,
        output: Path,
        projection: TmModelProjection.Result,
        provenance: software.amazon.smithy.model.node.ObjectNode = Node.objectNode(),
    ) {
        val manifest = FileManifest.create(output.resolve("model"))
        generated.files.sorted().forEach { file ->
            val relative = generated.baseDir.relativize(file).toString()
            val destination = when {
                relative == "Cargo.toml" -> relative
                relative == "member-policy.json" -> relative
                relative == "src/model.rs" -> "src/model/mod.rs"
                relative.startsWith("src/model/") -> relative
                relative == "src/error.rs" -> "src/model/error.rs"
                else -> return@forEach
            }
            val content = Files.readString(file).replace("crate::error::", "crate::model::error::") +
                if (relative == "Cargo.toml") """

                    [workspace]

                    [lints.rust]
                    unexpected_cfgs = { level = "warn", check-cfg = ['cfg(s3_tm_out_of_tree)'] }
                """.trimIndent() + "\n" else ""
            manifest.writeFile(destination, content)
        }
        val root = manifest.baseDir.resolve("src/model/mod.rs")
        manifest.writeFile(
            "src/model/mod.rs",
            Files.readString(root) + "\n/// Enum parsing errors.\npub mod error;\n",
        )
        manifest.writeFile("src/lib.rs", "// Code generated by s3-tm-model-codegen. DO NOT EDIT.\npub mod model;\n")
        manifest.writeFile(
            "build.rs",
            """
                // Code generated by s3-tm-model-codegen. DO NOT EDIT.
                fn main() {
                    println!("cargo:rustc-cfg=s3_tm_out_of_tree");
                }
            """.trimIndent() + "\n",
        )
        val sources = Node.objectNodeBuilder()
        projection.memberSources.forEach { (member, originals) ->
            sources.withMember(member.toString(), Node.fromStrings(originals.map { it.toString() }))
        }
        manifest.writeFile("member-sources.json", Node.prettyPrintJson(sources.build()) + "\n")
        manifest.writeFile("provenance.json", Node.prettyPrintJson(provenance) + "\n")
        val cargo = Files.readString(manifest.baseDir.resolve("Cargo.toml"))
        val rustDependencies = Node.objectNodeBuilder()
        Regex("(?ms)^\\[dependencies\\.([^]]+)]\\n(.*?)(?=^\\[|\\z)").findAll(cargo).forEach { dependency ->
            val name = dependency.groupValues[1]
            require(!name.startsWith("aws-sdk-")) { "Generated value artifact depends on SDK client $name" }
            rustDependencies.withMember(name, dependency.groupValues[2].trim())
        }
        manifest.writeFile("dependencies.json", Node.prettyPrintJson(
            Node.objectNodeBuilder().withMember("rust", rustDependencies.build())
                .withMember("cargoManifestSha256", GeneratedOutput.digest(cargo.toByteArray()))
                .withMember("generator", Node.objectNodeBuilder()
                    .withMember("smithy", System.getProperty("s3tm.smithyVersion", "unspecified"))
                    .withMember("smithy-rs", System.getProperty("s3tm.smithyRsVersion", "unspecified")).build()).build(),
        ) + "\n")
        val process = ProcessBuilder("cargo", "fmt", "--manifest-path", manifest.baseDir.resolve("Cargo.toml").toString())
            .inheritIO().start()
        check(process.waitFor() == 0) { "Formatting generated model failed" }
    }

    internal fun summary(
        input: Path,
        inputDescription: String,
        config: Path,
        output: Path,
        buildOutput: Path,
        inputOperations: Int,
        operations: List<String>,
        projectOnly: Boolean,
    ): String = buildString {
        appendLine("S3 model codegen output")
        appendLine("Input model:           $input ($inputDescription)")
        appendLine("Projection config:     $config")
        appendLine("Projection:            ${ModelProjection.name}")
        appendLine("Output root:           $output")
        appendLine("Projection output dir: ${output.resolve(ModelProjection.name)}")
        appendLine("Projected model:       ${output.resolve("${ModelProjection.name}/model/model.json")}")
        appendLine("Operations:            $inputOperations input -> ${operations.size} retained")
        appendLine("Retained operations:   ${operations.sorted().joinToString(", ")}")
        if (projectOnly) {
            appendLine("Mode:                  project-only (Rust generation skipped)")
        } else {
            appendLine("Codegen work dir:      ${buildOutput.resolve("raw")}")
            appendLine("Generated crate:       ${output.resolve("model")}")
            appendLine("Generated module:      ${output.resolve("model/src/model/mod.rs")}")
        }
    }
}

fun main(args: Array<String>) {
    require(args.size == 7) {
        "Usage: ModelArtifact <input> <config> <output> <build-output> <smithy-types-version> <project-only> <input-description>"
    }
    Logger.getLogger("software.amazon.smithy").level = Level.WARNING
    val input = Path.of(args[0]).toAbsolutePath().normalize()
    val config = Path.of(args[1]).toAbsolutePath().normalize()
    val output = Path.of(args[2]).toAbsolutePath().normalize()
    val buildOutput = Path.of(args[3]).toAbsolutePath().normalize()
    val projectOnly = args[5].toBooleanStrict()
    val source = ModelLoader.load(input)
    Files.createDirectories(buildOutput)
    val temporary = Files.createTempDirectory(buildOutput, "candidate-")
    val candidate = temporary.resolve("artifact")
    try {
        val dataplane = ModelProjection.build(source, config, candidate)
        val modelFile = dataplane.getPluginManifest("model").orElseThrow().baseDir.resolve("model.json")
        val model = ModelLoader.load(modelFile)
        if (!projectOnly) {
            val projection = TmModelProjection.project(model)
            val generated = ModelGenerator.generate(projection, temporary.resolve("raw"), args[4])
            GeneratedOutput.publish(generated.baseDir, buildOutput.resolve("raw"), raw = true)
            val generatorFiles = Files.walk(config.parent.resolve("src/main/kotlin")).use { paths ->
                paths.filter(Files::isRegularFile).sorted().toList()
            } + listOf("build.gradle.kts", "settings.gradle.kts", "gradle.properties", "gradle/wrapper/gradle-wrapper.properties")
                .map { config.parent.resolve(it) }
            val generatorDigest = GeneratedOutput.digest(generatorFiles.flatMap { file ->
                (config.parent.relativize(file).toString() + "\u0000").toByteArray().toList() +
                    Files.readAllBytes(file).toList()
            }.toByteArray())
            val provenance = Node.objectNodeBuilder().withMember("schemaVersion", 1)
                .withMember("generator", GeneratedOutput.generator)
                .withMember("generatorSha256", generatorDigest)
                .withMember("source", args[6])
                .withMember("inputSha256", GeneratedOutput.digest(Files.readAllBytes(input)))
                .withMember("projectionConfigSha256", GeneratedOutput.digest(Files.readAllBytes(config)))
                .withMember("projectedModelSha256", GeneratedOutput.digest(Files.readAllBytes(modelFile)))
                .withMember("roots", Node.fromStrings(projection.roots.map { it.toString() }.sorted()))
                .build()
            ModelArtifact.assemble(generated, candidate, projection, provenance)
        }
        GeneratedOutput.publish(candidate, output, projectOnly)
        println(ModelArtifact.summary(
            input, args[6], config, output, buildOutput,
            source.expectShape(ModelLoader.serviceId, software.amazon.smithy.model.shapes.ServiceShape::class.java).operations.size,
            model.operationShapes.map { it.id.name }, projectOnly,
        ))
    } finally {
        GeneratedOutput.removeTemporary(temporary)
    }
}
