/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
package software.amazon.s3tm.codegen

import java.nio.file.Files
import java.nio.file.Path
import java.util.logging.Level
import java.util.logging.Logger
import software.amazon.smithy.build.FileManifest
import software.amazon.smithy.model.node.Node

/** Assembles a standalone crate with the complete generated subtree at src/model. */
object ModelArtifact {
    fun assemble(generated: FileManifest, output: Path, projection: TmModelProjection.Result) {
        val manifest = FileManifest.create(output.resolve("model"))
        generated.files.sorted().forEach { file ->
            val relative = generated.baseDir.relativize(file).toString()
            val destination = when {
                relative == "Cargo.toml" -> relative
                relative == "src/model.rs" -> "src/model/mod.rs"
                relative.startsWith("src/model/") -> relative
                relative == "src/error.rs" -> "src/model/error.rs"
                else -> return@forEach
            }
            val content = Files.readString(file).replace("crate::error::", "crate::model::error::") +
                if (relative == "Cargo.toml") "\n[workspace]\n" else ""
            manifest.writeFile(destination, content)
        }
        val root = manifest.baseDir.resolve("src/model/mod.rs")
        manifest.writeFile(
            "src/model/mod.rs",
            Files.readString(root) + "\n/// Enum parsing errors.\npub mod error;\n",
        )
        manifest.writeFile("src/lib.rs", "// Code generated by s3-tm-model-codegen. DO NOT EDIT.\npub mod model;\n")
        val sources = Node.objectNodeBuilder()
        projection.memberSources.forEach { (member, originals) ->
            sources.withMember(member.toString(), Node.fromStrings(originals.map { it.toString() }))
        }
        manifest.writeFile("member-sources.json", Node.prettyPrintJson(sources.build()) + "\n")
        val process = ProcessBuilder("cargo", "fmt", "--manifest-path", manifest.baseDir.resolve("Cargo.toml").toString())
            .inheritIO().start()
        check(process.waitFor() == 0) { "Formatting generated model failed" }
    }

    internal fun summary(
        input: Path,
        inputDescription: String,
        config: Path,
        output: Path,
        buildOutput: Path,
        inputOperations: Int,
        operations: List<String>,
        projectOnly: Boolean,
    ): String = buildString {
        appendLine("S3 model codegen output")
        appendLine("Input model:           $input ($inputDescription)")
        appendLine("Projection config:     $config")
        appendLine("Projection:            ${ModelProjection.name}")
        appendLine("Output root:           $output")
        appendLine("Projection output dir: ${output.resolve(ModelProjection.name)}")
        appendLine("Projected model:       ${output.resolve("${ModelProjection.name}/model/model.json")}")
        appendLine("Operations:            $inputOperations input -> ${operations.size} retained")
        appendLine("Retained operations:   ${operations.sorted().joinToString(", ")}")
        if (projectOnly) {
            appendLine("Mode:                  project-only (Rust generation skipped)")
        } else {
            appendLine("Codegen work dir:      $buildOutput")
            appendLine("Generated crate:       ${output.resolve("model")}")
            appendLine("Generated module:      ${output.resolve("model/src/model/mod.rs")}")
        }
    }
}

fun main(args: Array<String>) {
    require(args.size == 7) {
        "Usage: ModelArtifact <input> <config> <output> <build-output> <smithy-types-version> <project-only> <input-description>"
    }
    Logger.getLogger("software.amazon.smithy").level = Level.WARNING
    val input = Path.of(args[0]).toAbsolutePath().normalize()
    val config = Path.of(args[1]).toAbsolutePath().normalize()
    val output = Path.of(args[2]).toAbsolutePath().normalize()
    val buildOutput = Path.of(args[3]).toAbsolutePath().normalize()
    val projectOnly = args[5].toBooleanStrict()
    val source = ModelLoader.load(input)
    val dataplane = ModelProjection.build(source, config, output)
    val modelFile = dataplane.getPluginManifest("model").orElseThrow().baseDir.resolve("model.json")
    val model = ModelLoader.load(modelFile)
    if (!projectOnly) {
        val projection = TmModelProjection.project(model)
        val generated = ModelGenerator.generate(projection, buildOutput, args[4])
        ModelArtifact.assemble(generated, output, projection)
    }
    println(ModelArtifact.summary(
        input, args[6], config, output, buildOutput,
        source.expectShape(ModelLoader.serviceId, software.amazon.smithy.model.shapes.ServiceShape::class.java).operations.size,
        model.operationShapes.map { it.id.name }, projectOnly,
    ))
}
