#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

from model_source import main

if __name__ == "__main__":
    raise SystemExit(main())
