# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate and install the modeled values and SDK v1 adapter subtrees."""

import argparse
import contextlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import codegen
from model_source import REPOSITORY_ROOT


DESTINATION = Path("aws-sdk-s3-transfer-manager/src/model")
CANDIDATE = Path("model/src/model")
SDK_DESTINATION = Path("aws-sdk-s3-transfer-manager/src/sdk_v1")
SDK_CANDIDATE = Path("sdk_v1")
TREES = ((DESTINATION, CANDIDATE), (SDK_DESTINATION, SDK_CANDIDATE))
GENERATED_PREFIX = b"// Code generated by "


def checked_directory(root: Path, relative: Path) -> Path:
    """Validate directory parents without resolving away symlinks."""
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise OSError(f"installation path must stay inside its root: {relative}")
    target = root / relative
    current = target
    while current != root:
        if current.is_symlink():
            raise OSError(f"refusing symlink installation path: {current}")
        if current.exists() and not current.is_dir():
            raise OSError(f"installation path is not a directory: {current}")
        current = current.parent
    return target


def destination(root: Path) -> Path:
    """Resolve only the fixed installation path."""
    return checked_directory(root, DESTINATION)


@contextlib.contextmanager
def installation_lock(root: Path):
    directory = checked_directory(root, Path("target/codegen"))
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "install-model.lock"
    try:
        descriptor = os.open(path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError as error:
        raise OSError(f"installation is locked: {path}; remove a stale lock only after checking for another installer") from error
    try:
        yield
    finally:
        owned = os.fstat(descriptor)
        os.close(descriptor)
        if (path.exists() or path.is_symlink()) and (path.lstat().st_dev, path.lstat().st_ino) == (owned.st_dev, owned.st_ino):
            path.unlink()


def inventory(directory: Path, missing_ok: bool = False, sdk_artifact: bool = False) -> dict:
    """Read a generated Rust tree, rejecting foreign files and links before copying."""
    if directory.is_symlink():
        raise OSError(f"refusing symlink model directory: {directory}")
    if not directory.exists():
        if missing_ok:
            return {}
        raise OSError(f"missing generated model directory: {directory}")
    if not directory.is_dir():
        raise OSError(f"model directory is not a directory: {directory}")
    files = {}
    for parent, directories, names in os.walk(directory, followlinks=False):
        for name in directories + names:
            path = Path(parent) / name
            if path.is_symlink():
                raise OSError(f"refusing symlink model entry: {path}")
        for name in names:
            path = Path(parent) / name
            if not path.is_file():
                raise OSError(f"model entry is not a regular file: {path}")
            content = path.read_bytes()
            if sdk_artifact and path == directory / "mapping.json":
                continue
            header = content.split(b"\n", 1)[0]
            if path.suffix != ".rs" or not header.startswith(GENERATED_PREFIX) or not header.endswith(b"DO NOT EDIT."):
                raise OSError(f"refusing handwritten or unmarked model file: {path}")
            files[path.relative_to(directory).as_posix()] = content
    return dict(sorted(files.items()))


def changes(old: dict, new: dict) -> list:
    result = []
    for name in sorted(old.keys() | new.keys()):
        if name not in old:
            result.append(("Added", name))
        elif name not in new:
            result.append(("Removed", name))
        elif old[name] != new[name]:
            result.append(("Changed", name))
    return result


def dirty_files(root: Path) -> set:
    """Include staged, unstaged, deleted, and untracked destination files."""
    commands = (
        ["diff", "--name-only", "--no-renames", "-z", "HEAD", "--", *(item[0].as_posix() for item in TREES)],
        ["ls-files", "--others", "-z", "--", *(item[0].as_posix() for item in TREES)],
    )
    files = set()
    for args in commands:
        result = subprocess.run(
            ["git", "-C", str(root)] + args, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        )
        if result.returncode:
            raise OSError(f"cannot inspect generated-file edits: {os.fsdecode(result.stderr).strip()}")
        files.update(os.fsdecode(name) for name in result.stdout.split(b"\0") if name)
    return files


def publish(root: Path, trees: list, overwrite: bool) -> None:
    """Preflight and stage both trees, then install with rollback across both."""
    with installation_lock(root):
        publish_locked(root, trees, overwrite)


def publish_locked(root: Path, trees: list, overwrite: bool) -> None:
    changed = [(relative, target, old, new) for relative, target, old, new in trees if changes(old, new)]
    if not changed:
        return
    if not overwrite:
        dirty = dirty_files(root)
        conflicts = [
            (relative / name).as_posix()
            for relative, _, old, new in changed for _, name in changes(old, new)
            if (relative / name).as_posix() in dirty
        ]
        if conflicts:
            raise OSError(
                "locally edited generated files would be replaced: " + ", ".join(conflicts) +
                "; review --dry-run and use --overwrite to replace them explicitly"
            )
    prepared = []
    succeeded = False
    try:
        for relative, target, old, new in changed:
            checked_directory(root, relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            temporary = Path(tempfile.mkdtemp(prefix=".s3-tm-model-", dir=target.parent))
            state = {"target": target, "temporary": temporary, "backup": temporary / "previous",
                     "staging": temporary / "candidate", "swap_started": False}
            prepared.append(state)
            state["staging"].mkdir()
            for name, content in new.items():
                path = state["staging"] / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
        # Detect edits made while the candidate was being assembled.
        for relative, target, old, _ in trees:
            checked_directory(root, relative)
            if inventory(target, missing_ok=True) != old:
                raise OSError("installed source changed during publication; retry after reviewing the edits")
        try:
            for state in prepared:
                target = state["target"]
                if target.exists():
                    os.replace(target, state["backup"])
                state["swap_started"] = True
                os.replace(state["staging"], target)
            succeeded = True
        except BaseException as error:
            failures = []
            for state in reversed(prepared):
                try:
                    if state["backup"].exists():
                        if state["target"].exists():
                            restore(state)
                        else:
                            os.replace(state["backup"], state["target"])
                    elif state["swap_started"] and not state["staging"].exists() and state["target"].exists():
                        shutil.rmtree(state["target"])
                except BaseException as rollback_error:
                    failures.append(f"{state['backup']}: {rollback_error}")
            if failures:
                raise OSError("installation and rollback failed; previous files preserved at " + "; ".join(failures)) from error
            raise
    finally:
        # Never discard the old tree after an unsuccessful or interrupted swap.
        for state in prepared:
            if succeeded or not state["backup"].exists():
                shutil.rmtree(state["temporary"])


def restore(state: dict) -> None:
    """Move an installed candidate aside so a nonempty previous tree can return."""
    os.replace(state["target"], state["temporary"] / "discarded")
    os.replace(state["backup"], state["target"])


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate fresh modeled values and SDK adapters; install both fixed TM subtrees."
    )
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--dry-run", action="store_true", help="report source changes without installing")
    modes.add_argument("--check", action="store_true", help="exit 1 if installed files differ; never install")
    parser.add_argument("--model", type=Path, help="explicit local Smithy model input")
    parser.add_argument("--offline", action="store_true", help="forbid dependency/model fetching")
    parser.add_argument("--pinned-only", action="store_true", help="reject local model overrides")
    parser.add_argument("--overwrite", action="store_true", help="replace locally edited generated files")
    options = parser.parse_args(argv)
    if options.pinned_only and options.model is not None:
        parser.error("--pinned-only does not accept --model overrides")
    if options.overwrite and (options.check or options.dry_run):
        parser.error("--overwrite is only meaningful when installing")
    try:
        trees = []
        for relative, candidate in TREES:
            target = checked_directory(REPOSITORY_ROOT, relative)
            old = inventory(target, missing_ok=True)
            trees.append((relative, target, old, candidate))
            print(f"Install destination: {target}", flush=True)
        with tempfile.TemporaryDirectory(prefix="s3-tm-install-model-") as temporary:
            scratch = Path(temporary)
            print(f"Fresh artifact root: {scratch} (removed after installation/comparison)", flush=True)
            arguments = ["--output", str(scratch)]
            if options.model is not None:
                arguments += ["--model", str(options.model)]
            if options.offline:
                arguments.append("--offline")
            if options.pinned_only:
                arguments.append("--pinned-only")
            status = codegen.main(arguments)
            if status:
                return status
            candidates = []
            affected = []
            for relative, target, old, candidate in trees:
                new = inventory(checked_directory(scratch, candidate), sdk_artifact=candidate == SDK_CANDIDATE)
                if "mod.rs" not in new:
                    raise OSError(f"generated {candidate} is missing mod.rs")
                candidates.append((relative, target, old, new))
                for action, name in changes(old, new):
                    print(f"{action}: {relative / name}")
                    affected.append((action, relative / name))
            if not affected:
                print("Installed generated source unchanged.")
                return 0
            if options.check:
                print("Check: installed source unchanged.")
                return 1
            if options.dry_run:
                print("Dry run: installed source unchanged.")
                return 0
            publish(REPOSITORY_ROOT, candidates, options.overwrite)
            for _, target, _, new in candidates:
                print(f"Installed {len(new)} generated Rust files at {target}.")
            return 0
    except OSError as error:
        print(f"install-model: {error}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("install-model: interrupted", file=sys.stderr)
        return 130
