# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

org.gradle.jvmargs=-Xmx1g
org.gradle.workers.max=2
kotlin.code.style=official
kotlin.version=2.1.0
smithy.version=1.73.0
smithy.rs.version=0.1.24
junit.version=5.10.5
junit.platform.version=1.10.5

# Pinned model input.
model.repository=smithy-lang/smithy-rs
model.path=aws/sdk/aws-models/s3.json
model.revision=f45327599be30e25bc171df60a01511a81d0f682
model.sha256=3e7e6a41c4ac91e340aee7be88b4a1428b8cf93dd3fbb122e2211170831e3a0c
