// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When matching `ChecksumAlgorithm`, handle known variants and retain a wildcard
/// arm for values introduced by S3 after this crate was generated.
///
/// To recognize a value that is not yet a named variant, use `as_str()`:
///
/// ```text
/// match value {
///     // Handle known variants here.
///     other if other.as_str() == "NewFeature" => { /* ... */ },
///     _ => { /* ... */ },
/// }
/// ```
///
/// This continues to recognize `"NewFeature"` if a future version of this crate
/// adds a named variant for it. Avoid matching `Unknown` directly: its inner
/// value is opaque, and that arm would no longer match the new named variant.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::Eq,
    ::std::cmp::Ord,
    ::std::cmp::PartialEq,
    ::std::cmp::PartialOrd,
    ::std::fmt::Debug,
    ::std::hash::Hash,
)]
pub enum ChecksumAlgorithm {
    #[allow(missing_docs)] // documentation missing in model
    Crc32,
    #[allow(missing_docs)] // documentation missing in model
    Crc32C,
    #[allow(missing_docs)] // documentation missing in model
    Crc64Nvme,
    #[allow(missing_docs)] // documentation missing in model
    Md5,
    #[allow(missing_docs)] // documentation missing in model
    Sha1,
    #[allow(missing_docs)] // documentation missing in model
    Sha256,
    #[allow(missing_docs)] // documentation missing in model
    Sha512,
    #[allow(missing_docs)] // documentation missing in model
    Xxhash128,
    #[allow(missing_docs)] // documentation missing in model
    Xxhash3,
    #[allow(missing_docs)] // documentation missing in model
    Xxhash64,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(
        note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants."
    )]
    Unknown(crate::model::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for ChecksumAlgorithm {
    fn from(s: &str) -> Self {
        match s {
            "CRC32" => ChecksumAlgorithm::Crc32,
            "CRC32C" => ChecksumAlgorithm::Crc32C,
            "CRC64NVME" => ChecksumAlgorithm::Crc64Nvme,
            "MD5" => ChecksumAlgorithm::Md5,
            "SHA1" => ChecksumAlgorithm::Sha1,
            "SHA256" => ChecksumAlgorithm::Sha256,
            "SHA512" => ChecksumAlgorithm::Sha512,
            "XXHASH128" => ChecksumAlgorithm::Xxhash128,
            "XXHASH3" => ChecksumAlgorithm::Xxhash3,
            "XXHASH64" => ChecksumAlgorithm::Xxhash64,
            other => ChecksumAlgorithm::Unknown(
                crate::model::sealed_enum_unknown::UnknownVariantValue(other.to_owned()),
            ),
        }
    }
}
impl ::std::str::FromStr for ChecksumAlgorithm {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(ChecksumAlgorithm::from(s))
    }
}
impl ChecksumAlgorithm {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            ChecksumAlgorithm::Crc32 => "CRC32",
            ChecksumAlgorithm::Crc32C => "CRC32C",
            ChecksumAlgorithm::Crc64Nvme => "CRC64NVME",
            ChecksumAlgorithm::Md5 => "MD5",
            ChecksumAlgorithm::Sha1 => "SHA1",
            ChecksumAlgorithm::Sha256 => "SHA256",
            ChecksumAlgorithm::Sha512 => "SHA512",
            ChecksumAlgorithm::Xxhash128 => "XXHASH128",
            ChecksumAlgorithm::Xxhash3 => "XXHASH3",
            ChecksumAlgorithm::Xxhash64 => "XXHASH64",
            ChecksumAlgorithm::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &[
            "CRC32",
            "CRC32C",
            "CRC64NVME",
            "MD5",
            "SHA1",
            "SHA256",
            "SHA512",
            "XXHASH128",
            "XXHASH3",
            "XXHASH64",
        ]
    }
}
impl ::std::convert::AsRef<str> for ChecksumAlgorithm {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl ChecksumAlgorithm {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(
        value: &str,
    ) -> ::std::result::Result<Self, crate::model::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => {
                ::std::result::Result::Err(crate::model::error::UnknownVariantError::new(value))
            }
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for ChecksumAlgorithm {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ChecksumAlgorithm::Crc32 => write!(f, "CRC32"),
            ChecksumAlgorithm::Crc32C => write!(f, "CRC32C"),
            ChecksumAlgorithm::Crc64Nvme => write!(f, "CRC64NVME"),
            ChecksumAlgorithm::Md5 => write!(f, "MD5"),
            ChecksumAlgorithm::Sha1 => write!(f, "SHA1"),
            ChecksumAlgorithm::Sha256 => write!(f, "SHA256"),
            ChecksumAlgorithm::Sha512 => write!(f, "SHA512"),
            ChecksumAlgorithm::Xxhash128 => write!(f, "XXHASH128"),
            ChecksumAlgorithm::Xxhash3 => write!(f, "XXHASH3"),
            ChecksumAlgorithm::Xxhash64 => write!(f, "XXHASH64"),
            ChecksumAlgorithm::Unknown(value) => write!(f, "{value}"),
        }
    }
}
