// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When matching `RequestPayer`, handle known variants and retain a wildcard
/// arm for values introduced by S3 after this crate was generated.
///
/// To recognize a value that is not yet a named variant, use `as_str()`:
///
/// ```text
/// match value {
///     // Handle known variants here.
///     other if other.as_str() == "NewFeature" => { /* ... */ },
///     _ => { /* ... */ },
/// }
/// ```
///
/// This continues to recognize `"NewFeature"` if a future version of this crate
/// adds a named variant for it. Avoid matching `Unknown` directly: its inner
/// value is opaque, and that arm would no longer match the new named variant.
/// <p>Confirms that the requester knows that they will be charged for the request. Bucket owners need not
/// specify this parameter in their requests. If either the source or destination S3 bucket has Requester
/// Pays enabled, the requester will pay for the corresponding charges. For information about
/// downloading objects from Requester Pays buckets, see <a href="https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html">Downloading Objects in Requester Pays
/// Buckets</a> in the <i>Amazon S3 User Guide</i>.</p>
/// <note>
/// <p>This functionality is not supported for directory buckets.</p>
/// </note>
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::Eq,
    ::std::cmp::Ord,
    ::std::cmp::PartialEq,
    ::std::cmp::PartialOrd,
    ::std::fmt::Debug,
    ::std::hash::Hash,
)]
pub enum RequestPayer {
    #[allow(missing_docs)] // documentation missing in model
    Requester,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(
        note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants."
    )]
    Unknown(crate::model::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for RequestPayer {
    fn from(s: &str) -> Self {
        match s {
            "requester" => RequestPayer::Requester,
            other => RequestPayer::Unknown(crate::model::sealed_enum_unknown::UnknownVariantValue(
                other.to_owned(),
            )),
        }
    }
}
impl ::std::str::FromStr for RequestPayer {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(RequestPayer::from(s))
    }
}
impl RequestPayer {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            RequestPayer::Requester => "requester",
            RequestPayer::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &["requester"]
    }
}
impl ::std::convert::AsRef<str> for RequestPayer {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl RequestPayer {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(
        value: &str,
    ) -> ::std::result::Result<Self, crate::model::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => {
                ::std::result::Result::Err(crate::model::error::UnknownVariantError::new(value))
            }
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for RequestPayer {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            RequestPayer::Requester => write!(f, "requester"),
            RequestPayer::Unknown(value) => write!(f, "{value}"),
        }
    }
}
