// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// When matching `ServerSideEncryption`, handle known variants and retain a wildcard
/// arm for values introduced by S3 after this crate was generated.
///
/// To recognize a value that is not yet a named variant, use `as_str()`:
///
/// ```text
/// match value {
///     // Handle known variants here.
///     other if other.as_str() == "NewFeature" => { /* ... */ },
///     _ => { /* ... */ },
/// }
/// ```
///
/// This continues to recognize `"NewFeature"` if a future version of this crate
/// adds a named variant for it. Avoid matching `Unknown` directly: its inner
/// value is opaque, and that arm would no longer match the new named variant.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::Eq,
    ::std::cmp::Ord,
    ::std::cmp::PartialEq,
    ::std::cmp::PartialOrd,
    ::std::fmt::Debug,
    ::std::hash::Hash,
)]
pub enum ServerSideEncryption {
    #[allow(missing_docs)] // documentation missing in model
    Aes256,
    #[allow(missing_docs)] // documentation missing in model
    AwsFsx,
    #[allow(missing_docs)] // documentation missing in model
    AwsKms,
    #[allow(missing_docs)] // documentation missing in model
    AwsKmsDsse,
    /// `Unknown` contains new variants that have been added since this code was generated.
    #[deprecated(
        note = "Don't directly match on `Unknown`. See the docs on this enum for the correct way to handle unknown variants."
    )]
    Unknown(crate::model::sealed_enum_unknown::UnknownVariantValue),
}
impl ::std::convert::From<&str> for ServerSideEncryption {
    fn from(s: &str) -> Self {
        match s {
            "AES256" => ServerSideEncryption::Aes256,
            "aws:fsx" => ServerSideEncryption::AwsFsx,
            "aws:kms" => ServerSideEncryption::AwsKms,
            "aws:kms:dsse" => ServerSideEncryption::AwsKmsDsse,
            other => ServerSideEncryption::Unknown(
                crate::model::sealed_enum_unknown::UnknownVariantValue(other.to_owned()),
            ),
        }
    }
}
impl ::std::str::FromStr for ServerSideEncryption {
    type Err = ::std::convert::Infallible;

    fn from_str(s: &str) -> ::std::result::Result<Self, <Self as ::std::str::FromStr>::Err> {
        ::std::result::Result::Ok(ServerSideEncryption::from(s))
    }
}
impl ServerSideEncryption {
    /// Returns the `&str` value of the enum member.
    pub fn as_str(&self) -> &str {
        match self {
            ServerSideEncryption::Aes256 => "AES256",
            ServerSideEncryption::AwsFsx => "aws:fsx",
            ServerSideEncryption::AwsKms => "aws:kms",
            ServerSideEncryption::AwsKmsDsse => "aws:kms:dsse",
            ServerSideEncryption::Unknown(value) => value.as_str(),
        }
    }
    /// Returns all the `&str` representations of the enum members.
    pub const fn values() -> &'static [&'static str] {
        &["AES256", "aws:fsx", "aws:kms", "aws:kms:dsse"]
    }
}
impl ::std::convert::AsRef<str> for ServerSideEncryption {
    fn as_ref(&self) -> &str {
        self.as_str()
    }
}
impl ServerSideEncryption {
    /// Parses the enum value while disallowing unknown variants.
    ///
    /// Unknown variants will result in an error.
    pub fn try_parse(
        value: &str,
    ) -> ::std::result::Result<Self, crate::model::error::UnknownVariantError> {
        match Self::from(value) {
            #[allow(deprecated)]
            Self::Unknown(_) => {
                ::std::result::Result::Err(crate::model::error::UnknownVariantError::new(value))
            }
            known => Ok(known),
        }
    }
}
impl ::std::fmt::Display for ServerSideEncryption {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        match self {
            ServerSideEncryption::Aes256 => write!(f, "AES256"),
            ServerSideEncryption::AwsFsx => write!(f, "aws:fsx"),
            ServerSideEncryption::AwsKms => write!(f, "aws:kms"),
            ServerSideEncryption::AwsKmsDsse => write!(f, "aws:kms:dsse"),
            ServerSideEncryption::Unknown(value) => write!(f, "{value}"),
        }
    }
}
