// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// The given enum value failed to parse since it is not a known value.
#[derive(Debug)]
pub struct UnknownVariantError {
    value: ::std::string::String,
}
impl UnknownVariantError {
    pub(crate) fn new(value: impl ::std::convert::Into<::std::string::String>) -> Self {
        Self {
            value: value.into(),
        }
    }
}
impl ::std::fmt::Display for UnknownVariantError {
    fn fmt(
        &self,
        f: &mut ::std::fmt::Formatter<'_>,
    ) -> ::std::result::Result<(), ::std::fmt::Error> {
        write!(f, "unknown enum variant: '{}'", self.value)
    }
}
impl ::std::error::Error for UnknownVariantError {}
