// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#![allow(deprecated)]
#![allow(unknown_lints)]
#![allow(clippy::module_inception)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::large_enum_variant)]
#![allow(clippy::wrong_self_convention)]
#![allow(clippy::should_implement_trait)]
#![allow(clippy::disallowed_names)]
#![allow(clippy::vec_init_then_push)]
#![allow(clippy::type_complexity)]
#![allow(clippy::needless_return)]
#![allow(clippy::derive_partial_eq_without_eq)]
#![allow(clippy::result_large_err)]
#![allow(clippy::unnecessary_map_on_constructor)]
#![allow(clippy::useless_conversion)]
#![allow(clippy::deprecated_semver)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::redundant_explicit_links)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::invalid_html_tags)]
#![allow(elided_lifetimes_in_paths)]
#![forbid(unsafe_code)]

pub use crate::model::_archive_status::ArchiveStatus;

pub use crate::model::_checksum_algorithm::ChecksumAlgorithm;

pub use crate::model::_checksum_mode::ChecksumMode;

pub use crate::model::_checksum_type::ChecksumType;

pub use crate::model::_download_input::DownloadInput;

pub use crate::model::_object::Object;

pub use crate::model::_object_canned_acl::ObjectCannedAcl;

pub use crate::model::_object_lock_legal_hold_status::ObjectLockLegalHoldStatus;

pub use crate::model::_object_lock_mode::ObjectLockMode;

pub use crate::model::_object_storage_class::ObjectStorageClass;

pub use crate::model::_owner::Owner;

pub use crate::model::_upload_input::UploadInput;

pub use crate::model::_replication_status::ReplicationStatus;

pub use crate::model::_request_charged::RequestCharged;

pub use crate::model::_request_payer::RequestPayer;

pub use crate::model::_restore_status::RestoreStatus;

pub use crate::model::_server_side_encryption::ServerSideEncryption;

pub use crate::model::_storage_class::StorageClass;

pub use crate::model::_chunk_metadata::ChunkMetadata;

pub use crate::model::_object_metadata::ObjectMetadata;

pub use crate::model::_upload_output::UploadOutput;

/// Enum parsing errors.
mod _archive_status;

/// Enum parsing errors.
mod _checksum_algorithm;

/// Enum parsing errors.
mod _checksum_mode;

/// Enum parsing errors.
mod _checksum_type;

/// Enum parsing errors.
mod _chunk_metadata;

/// Enum parsing errors.
mod _download_input;

/// Enum parsing errors.
mod _object;

/// Enum parsing errors.
mod _object_canned_acl;

/// Enum parsing errors.
mod _object_lock_legal_hold_status;

/// Enum parsing errors.
mod _object_lock_mode;

/// Enum parsing errors.
mod _object_metadata;

/// Enum parsing errors.
mod _object_storage_class;

/// Enum parsing errors.
mod _owner;

/// Enum parsing errors.
mod _replication_status;

/// Enum parsing errors.
mod _request_charged;

/// Enum parsing errors.
mod _request_payer;

/// Enum parsing errors.
mod _restore_status;

/// Enum parsing errors.
mod _server_side_encryption;

/// Enum parsing errors.
mod _storage_class;

/// Enum parsing errors.
mod _upload_input;

/// Enum parsing errors.
mod _upload_output;

/// Builders for modeled S3 values.
pub mod builders;

/// Enum parsing errors.
pub(crate) mod sealed_enum_unknown;

/// Enum parsing errors.
pub mod error;
