[build]
# Share one `target` directory at the project root for all Cargo projects and workspaces in aws-sdk-s3-transfer-manager-rs
target-dir = "target"

[profile.profiling]
inherits = "release"
debug = true
