# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import contextlib
import io
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import install_model


HEADER = b"// Code generated by test-codegen. DO NOT EDIT.\n"


class InstallModelTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.target = self.root / install_model.DESTINATION
        self.target.parent.mkdir(parents=True)
        self.calls = []
        self.candidate = {"mod.rs": HEADER + b"pub struct Candidate;\n"}
        self.sdk_candidate = {"mod.rs": HEADER + b"// SDK candidate\n"}
        self.sdk_target = self.root / install_model.SDK_DESTINATION
        self.write_tree(self.sdk_target, self.sdk_candidate)
        self.status = 0
        self.addCleanup(patch.stopall)
        patch.object(install_model, "REPOSITORY_ROOT", self.root).start()
        patch.object(install_model.codegen, "main", side_effect=self.generate).start()
        patch.object(install_model, "dirty_files", return_value=set()).start()

    def generate(self, args):
        self.calls.append(list(args))
        output = Path(args[args.index("--output") + 1])
        if self.status:
            return self.status
        self.write_tree(output / install_model.CANDIDATE, self.candidate)
        self.write_tree(output / install_model.SDK_CANDIDATE, self.sdk_candidate)
        (output / install_model.SDK_CANDIDATE / "mapping.json").write_text("{}")
        # These standalone harness files must never be installed.
        (output / "model/Cargo.toml").write_text("[package]\nname='fixture'\n")
        (output / "model/build.rs").write_text("fn main() {}\n")
        return 0

    @staticmethod
    def write_tree(target, values):
        target.mkdir(parents=True, exist_ok=True)
        for name, value in values.items():
            file = target / name
            file.parent.mkdir(parents=True, exist_ok=True)
            file.write_bytes(value)

    def invoke(self, *args):
        output = io.StringIO()
        with contextlib.redirect_stdout(output), contextlib.redirect_stderr(output):
            status = install_model.main(list(args))
        return status, output.getvalue()

    def test_bootstrap_installs_only_complete_rust_subtree_from_fresh_generation(self):
        self.candidate["nested/helper.rs"] = HEADER + b"pub struct Helper;\n"
        status, output = self.invoke()
        self.assertEqual(0, status)
        self.assertEqual(self.candidate, install_model.inventory(self.target))
        self.assertIn("Installed 2 generated Rust files", output)
        self.assertFalse((self.target / "Cargo.toml").exists())
        self.assertFalse((self.target / "build.rs").exists())
        self.assertFalse(Path(self.calls[0][1]).exists())

    def test_all_modes_generate_fresh_output_even_when_installed_files_match(self):
        self.write_tree(self.target, self.candidate)
        for mode in ((), ("--check",), ("--dry-run",)):
            self.assertEqual(0, self.invoke(*mode)[0])
        self.assertEqual(3, len(self.calls))
        self.assertEqual(self.candidate, install_model.inventory(self.target))

    def test_noop_does_not_inspect_or_reject_dirty_identical_files(self):
        self.write_tree(self.target, self.candidate)
        install_model.dirty_files.side_effect = OSError("must not inspect")
        self.assertEqual(0, self.invoke()[0])
        self.assertFalse((self.root / "target/codegen/install-model.lock").exists())

    def test_preview_reports_complete_diff_without_changing_or_creating_source(self):
        self.assertEqual(0, self.invoke("--dry-run")[0])
        self.assertFalse(self.target.exists())
        original = {"mod.rs": HEADER + b"old\n", "stale.rs": HEADER + b"stale\n"}
        self.write_tree(self.target, original)
        self.candidate["added.rs"] = HEADER + b"added\n"
        status, output = self.invoke("--dry-run")
        self.assertEqual(0, status)
        for action in ("Added:", "Changed:", "Removed:"):
            self.assertIn(action, output)
        self.assertEqual(original, install_model.inventory(self.target))

    def test_check_missing_different_extra_and_matching_source_is_nonmutating(self):
        self.assertEqual(1, self.invoke("--check")[0])
        self.assertFalse(self.target.exists())
        original = {"mod.rs": HEADER + b"old\n", "stale.rs": HEADER}
        self.write_tree(self.target, original)
        self.assertEqual(1, self.invoke("--check")[0])
        self.assertEqual(original, install_model.inventory(self.target))
        (self.target / "stale.rs").unlink()
        (self.target / "mod.rs").write_bytes(self.candidate["mod.rs"])
        self.assertEqual(0, self.invoke("--check")[0])

    def test_clean_stale_files_are_removed_only_inside_generated_subtree(self):
        self.write_tree(self.target, {"mod.rs": HEADER + b"old\n", "stale.rs": HEADER})
        outside = self.target.parent / "manual.rs"
        outside.write_text("manual source")
        status, output = self.invoke()
        self.assertEqual(0, status)
        self.assertIn("Removed:", output)
        self.assertEqual(self.candidate, install_model.inventory(self.target))
        self.assertEqual("manual source", outside.read_text())

    def test_dirty_divergent_source_requires_explicit_overwrite(self):
        original = {"mod.rs": HEADER + b"user edit\n"}
        self.write_tree(self.target, original)
        install_model.dirty_files.return_value = {(install_model.DESTINATION / "mod.rs").as_posix()}
        status, output = self.invoke()
        self.assertEqual(1, status)
        self.assertIn("--overwrite", output)
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual(0, self.invoke("--dry-run")[0])
        self.assertEqual(0, self.invoke("--overwrite")[0])
        self.assertEqual(self.candidate, install_model.inventory(self.target))

    def test_overwrite_never_permits_handwritten_or_unmarked_files(self):
        self.write_tree(self.target, {"mod.rs": b"pub struct Manual;"})
        status, output = self.invoke("--overwrite")
        self.assertEqual(1, status)
        self.assertIn("handwritten or unmarked", output)
        self.assertEqual(b"pub struct Manual;", (self.target / "mod.rs").read_bytes())
        self.assertEqual([], self.calls)

    def test_foreign_nonrust_file_is_rejected_before_generation(self):
        self.write_tree(self.target, {"notes.md": b"handwritten notes"})
        self.assertEqual(1, self.invoke()[0])
        self.assertEqual([], self.calls)
        self.assertEqual(b"handwritten notes", (self.target / "notes.md").read_bytes())

    def test_destination_symlink_and_symlink_parent_cannot_redirect_installation(self):
        outside = self.root / "outside"
        outside.mkdir()
        self.target.symlink_to(outside, target_is_directory=True)
        self.assertEqual(1, self.invoke("--overwrite")[0])
        self.target.unlink()
        self.target.parent.rename(self.root / "original-src")
        self.target.parent.symlink_to(outside, target_is_directory=True)
        self.assertEqual(1, self.invoke()[0])
        self.assertEqual([], self.calls)
        self.assertEqual([], list(outside.iterdir()))

    def test_nested_symlinks_are_rejected_without_reading_targets(self):
        self.write_tree(self.target, self.candidate)
        outside = self.root / "manual.rs"
        outside.write_text("manual")
        (self.target / "linked.rs").symlink_to(outside)
        self.assertEqual(1, self.invoke("--overwrite")[0])
        self.assertEqual("manual", outside.read_text())
        self.assertEqual([], self.calls)

    def test_missing_module_and_foreign_candidate_fail_before_installation(self):
        for values in ({"helper.rs": HEADER}, {"mod.rs": b"unmarked"}, {}):
            self.candidate = values
            self.assertEqual(1, self.invoke()[0])
            self.assertFalse(self.target.exists())

    def test_candidate_symlink_parent_cannot_redirect_the_validated_inventory(self):
        self.write_tree(self.target, self.candidate)
        original = dict(self.candidate)

        def linked_candidate(args):
            scratch = Path(args[args.index("--output") + 1])
            (scratch / "model").symlink_to(self.target.parent, target_is_directory=True)
            return 0

        install_model.codegen.main.side_effect = linked_candidate
        status, output = self.invoke("--overwrite")
        self.assertEqual(1, status)
        self.assertIn("symlink", output)
        self.assertEqual(original, install_model.inventory(self.target))

    def test_directory_validation_rejects_absolute_and_escaping_paths(self):
        for path in (Path("/outside"), Path("../outside"), Path("model/../../outside"), Path(".")):
            with self.assertRaises(OSError):
                install_model.checked_directory(self.root, path)

    def test_concurrent_edit_is_preserved_even_with_overwrite(self):
        original = {"mod.rs": HEADER + b"old\n"}
        self.write_tree(self.target, original)
        edited = HEADER + b"concurrent edit\n"
        write_bytes = Path.write_bytes

        def edit_during_staging(path, content):
            result = write_bytes(path, content)
            if ".s3-tm-model-" in str(path):
                write_bytes(self.target / "mod.rs", edited)
            return result

        with patch.object(Path, "write_bytes", edit_during_staging):
            status, output = self.invoke("--overwrite")
        self.assertEqual(1, status)
        self.assertIn("changed during publication", output)
        self.assertEqual({"mod.rs": edited}, install_model.inventory(self.target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))

    def test_failed_staging_write_leaves_the_old_tree_in_place(self):
        original = {"mod.rs": HEADER + b"old\n"}
        self.write_tree(self.target, original)
        write_bytes = Path.write_bytes

        def fail_staging(path, content):
            if ".s3-tm-model-" in str(path):
                raise OSError("simulated disk full")
            return write_bytes(path, content)

        with patch.object(Path, "write_bytes", fail_staging):
            status, output = self.invoke()
        self.assertEqual(1, status)
        self.assertIn("simulated disk full", output)
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))

    def test_nonregular_destination_entries_are_rejected(self):
        if not hasattr(os, "mkfifo"):
            self.skipTest("requires FIFO support")
        self.target.mkdir()
        os.mkfifo(self.target / "pipe.rs")
        status, output = self.invoke()
        self.assertEqual(1, status)
        self.assertIn("not a regular file", output)
        self.assertEqual([], self.calls)

    def test_generator_failure_preserves_destination_and_cleans_temporary_output(self):
        self.write_tree(self.target, self.candidate)
        self.status = 9
        self.assertEqual(9, self.invoke()[0])
        self.assertEqual(self.candidate, install_model.inventory(self.target))
        self.assertFalse(Path(self.calls[0][1]).exists())

    def test_subprocess_errors_have_actionable_diagnostics_without_traceback(self):
        install_model.codegen.main.side_effect = OSError("generator unavailable")
        status, output = self.invoke()
        self.assertEqual(1, status)
        self.assertIn("generator unavailable", output)
        self.assertNotIn("Traceback", output)
        self.assertFalse(self.target.exists())

    def test_failed_publication_restores_previous_tree_and_removes_staging(self):
        original = {"mod.rs": HEADER + b"old\n"}
        self.write_tree(self.target, original)
        replace = os.replace

        def fail_candidate(source, target):
            if Path(source).name == "candidate":
                raise OSError("simulated swap failure")
            return replace(source, target)

        with patch.object(install_model.os, "replace", side_effect=fail_candidate):
            self.assertEqual(1, self.invoke()[0])
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))
        self.assertFalse((self.root / "target/codegen/install-model.lock").exists())

    def test_interrupted_publication_restores_previous_tree(self):
        original = {"mod.rs": HEADER + b"old\n"}
        self.write_tree(self.target, original)
        replace = os.replace

        def interrupt_after_backup(source, target):
            result = replace(source, target)
            if Path(target).name == "previous":
                raise KeyboardInterrupt
            return result

        with patch.object(install_model.os, "replace", side_effect=interrupt_after_backup):
            status, output = self.invoke()
        self.assertEqual(130, status)
        self.assertIn("interrupted", output)
        self.assertNotIn("Traceback", output)
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))
        self.assertFalse((self.root / "target/codegen/install-model.lock").exists())

    def test_failed_rollback_preserves_recoverable_previous_files(self):
        original = {"mod.rs": HEADER + b"old\n"}
        self.write_tree(self.target, original)
        replace = os.replace

        def fail_swap_and_restore(source, target):
            if Path(source).name in ("candidate", "previous"):
                raise OSError("simulated rollback failure")
            return replace(source, target)

        with patch.object(install_model.os, "replace", side_effect=fail_swap_and_restore):
            status, output = self.invoke()
        self.assertEqual(1, status)
        backup = next(self.target.parent.glob(".s3-tm-model-*/previous"))
        self.assertEqual(original, install_model.inventory(backup))
        self.assertIn(str(backup), output)

    def test_existing_installation_lock_is_preserved(self):
        lock = self.root / "target/codegen/install-model.lock"
        lock.parent.mkdir(parents=True)
        lock.write_text("another installer")
        self.assertEqual(1, self.invoke()[0])
        self.assertEqual("another installer", lock.read_text())
        self.assertFalse(self.target.exists())

    def test_rejects_destination_overrides_and_incompatible_flags_before_generation(self):
        for args in (
            ("--destination", str(self.root / "outside")),
            ("--output", str(self.root / "outside")),
            ("--check", "--dry-run"),
            ("--check", "--overwrite"),
            ("--dry-run", "--overwrite"),
            ("--pinned-only", "--model", "local.json"),
        ):
            with contextlib.redirect_stderr(io.StringIO()), self.assertRaises(SystemExit):
                install_model.main(list(args))
        self.assertEqual([], self.calls)

    def test_local_paths_and_offline_pin_flags_are_forwarded_without_shell_splitting(self):
        self.assertEqual(0, self.invoke("--model", "models/local input.json", "--offline")[0])
        self.assertIn("--offline", self.calls[0])
        self.assertIn("models/local input.json", self.calls[0])
        self.assertEqual(0, self.invoke("--pinned-only")[0])
        self.assertIn("--pinned-only", self.calls[1])

    def test_second_destination_preflight_blocks_first_install(self):
        (self.sdk_target / "manual.txt").write_text("manual")
        self.assertEqual(1, self.invoke("--overwrite")[0])
        self.assertFalse(self.target.exists())
        self.assertEqual([], self.calls)

    def test_second_tree_dirty_conflict_leaves_both_unchanged(self):
        original = {"mod.rs": HEADER + b"old model\n"}
        self.write_tree(self.target, original)
        self.sdk_candidate["mod.rs"] = HEADER + b"new sdk\n"
        install_model.dirty_files.return_value = {(install_model.SDK_DESTINATION / "mod.rs").as_posix()}
        self.assertEqual(1, self.invoke()[0])
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertNotEqual(self.sdk_candidate, install_model.inventory(self.sdk_target))

    def test_second_swap_failure_rolls_back_first_swap(self):
        original = {"mod.rs": HEADER + b"old model\n"}
        self.write_tree(self.target, original)
        sdk_original = install_model.inventory(self.sdk_target)
        self.sdk_candidate["mod.rs"] = HEADER + b"new sdk\n"
        replace = os.replace

        def fail_sdk_candidate(source, target):
            if Path(source).name == "candidate" and Path(target) == self.sdk_target:
                raise OSError("second tree swap failed")
            return replace(source, target)

        with patch.object(install_model.os, "replace", side_effect=fail_sdk_candidate):
            self.assertEqual(1, self.invoke()[0])
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual(sdk_original, install_model.inventory(self.sdk_target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))

    def test_sdk_report_is_not_installed_and_missing_sdk_module_blocks_both(self):
        self.assertEqual(0, self.invoke()[0])
        self.assertFalse((self.sdk_target / "mapping.json").exists())
        model_original = install_model.inventory(self.target)
        self.candidate["mod.rs"] = HEADER + b"changed model\n"
        self.sdk_candidate = {}
        self.assertEqual(1, self.invoke()[0])
        self.assertEqual(model_original, install_model.inventory(self.target))

    def test_interrupt_after_bootstrap_swap_removes_new_destination(self):
        replace = os.replace

        def interrupt_after_swap(source, target):
            result = replace(source, target)
            if Path(source).name == "candidate" and Path(target) == self.target:
                raise KeyboardInterrupt
            return result

        with patch.object(install_model.os, "replace", side_effect=interrupt_after_swap):
            self.assertEqual(130, self.invoke()[0])
        self.assertFalse(self.target.exists())
        self.assertEqual(self.sdk_candidate, install_model.inventory(self.sdk_target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))

    def test_interrupt_after_second_swap_restores_both_previous_trees(self):
        original = {"mod.rs": HEADER + b"old model\n"}
        self.write_tree(self.target, original)
        sdk_original = install_model.inventory(self.sdk_target)
        self.sdk_candidate["mod.rs"] = HEADER + b"new SDK\n"
        replace = os.replace

        def interrupt_after_sdk_swap(source, target):
            result = replace(source, target)
            if Path(source).name == "candidate" and Path(target) == self.sdk_target:
                raise KeyboardInterrupt
            return result

        with patch.object(install_model.os, "replace", side_effect=interrupt_after_sdk_swap):
            self.assertEqual(130, self.invoke()[0])
        self.assertEqual(original, install_model.inventory(self.target))
        self.assertEqual(sdk_original, install_model.inventory(self.sdk_target))
        self.assertEqual([], list(self.target.parent.glob(".s3-tm-model-*")))


class InstalledGitEditsTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.target = self.root / install_model.DESTINATION
        self.target.mkdir(parents=True)
        (self.target / "mod.rs").write_bytes(HEADER + b"original\n")
        self.git("init", "--quiet")
        self.git("add", ".")
        self.git(
            "-c", "user.name=Fixture", "-c", "user.email=fixture@example.test",
            "-c", "commit.gpgsign=false", "-c", "core.hooksPath=/dev/null",
            "commit", "-qm", "fixture",
        )

    def git(self, *args):
        subprocess.run(["git", "-C", str(self.root), *args], check=True, capture_output=True)

    def test_staged_unstaged_deleted_untracked_and_unrelated_edits_are_classified(self):
        path = (install_model.DESTINATION / "mod.rs").as_posix()
        self.assertEqual(set(), install_model.dirty_files(self.root))
        (self.root / "unrelated.txt").write_text("unrelated work")
        self.assertEqual(set(), install_model.dirty_files(self.root))
        (self.target / "mod.rs").write_bytes(HEADER + b"edited\n")
        self.assertEqual({path}, install_model.dirty_files(self.root))
        self.git("add", path)
        self.assertEqual({path}, install_model.dirty_files(self.root))
        (self.target / "mod.rs").unlink()
        self.assertEqual({path}, install_model.dirty_files(self.root))
        (self.target / "extra.rs").write_bytes(HEADER)
        self.assertEqual(
            {path, (install_model.DESTINATION / "extra.rs").as_posix()},
            install_model.dirty_files(self.root),
        )
