// Code generated by s3-tm-model-codegen. DO NOT EDIT.
impl From<crate::model::ArchiveStatus> for ::aws_sdk_s3::types::ArchiveStatus {
    fn from(value: crate::model::ArchiveStatus) -> Self {
        super::convert::archive_status_to_sdk(&value)
    }
}
impl From<&crate::model::ArchiveStatus> for ::aws_sdk_s3::types::ArchiveStatus {
    fn from(value: &crate::model::ArchiveStatus) -> Self {
        super::convert::archive_status_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ArchiveStatus> for crate::model::ArchiveStatus {
    fn from(value: ::aws_sdk_s3::types::ArchiveStatus) -> Self {
        super::convert::archive_status_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ArchiveStatus> for crate::model::ArchiveStatus {
    fn from(value: &::aws_sdk_s3::types::ArchiveStatus) -> Self {
        super::convert::archive_status_from_sdk(value)
    }
}
impl From<crate::model::ChecksumAlgorithm> for ::aws_sdk_s3::types::ChecksumAlgorithm {
    fn from(value: crate::model::ChecksumAlgorithm) -> Self {
        super::convert::checksum_algorithm_to_sdk(&value)
    }
}
impl From<&crate::model::ChecksumAlgorithm> for ::aws_sdk_s3::types::ChecksumAlgorithm {
    fn from(value: &crate::model::ChecksumAlgorithm) -> Self {
        super::convert::checksum_algorithm_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ChecksumAlgorithm> for crate::model::ChecksumAlgorithm {
    fn from(value: ::aws_sdk_s3::types::ChecksumAlgorithm) -> Self {
        super::convert::checksum_algorithm_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ChecksumAlgorithm> for crate::model::ChecksumAlgorithm {
    fn from(value: &::aws_sdk_s3::types::ChecksumAlgorithm) -> Self {
        super::convert::checksum_algorithm_from_sdk(value)
    }
}
impl From<crate::model::ChecksumMode> for ::aws_sdk_s3::types::ChecksumMode {
    fn from(value: crate::model::ChecksumMode) -> Self {
        super::convert::checksum_mode_to_sdk(&value)
    }
}
impl From<&crate::model::ChecksumMode> for ::aws_sdk_s3::types::ChecksumMode {
    fn from(value: &crate::model::ChecksumMode) -> Self {
        super::convert::checksum_mode_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ChecksumMode> for crate::model::ChecksumMode {
    fn from(value: ::aws_sdk_s3::types::ChecksumMode) -> Self {
        super::convert::checksum_mode_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ChecksumMode> for crate::model::ChecksumMode {
    fn from(value: &::aws_sdk_s3::types::ChecksumMode) -> Self {
        super::convert::checksum_mode_from_sdk(value)
    }
}
impl From<crate::model::ChecksumType> for ::aws_sdk_s3::types::ChecksumType {
    fn from(value: crate::model::ChecksumType) -> Self {
        super::convert::checksum_type_to_sdk(&value)
    }
}
impl From<&crate::model::ChecksumType> for ::aws_sdk_s3::types::ChecksumType {
    fn from(value: &crate::model::ChecksumType) -> Self {
        super::convert::checksum_type_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ChecksumType> for crate::model::ChecksumType {
    fn from(value: ::aws_sdk_s3::types::ChecksumType) -> Self {
        super::convert::checksum_type_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ChecksumType> for crate::model::ChecksumType {
    fn from(value: &::aws_sdk_s3::types::ChecksumType) -> Self {
        super::convert::checksum_type_from_sdk(value)
    }
}
impl From<crate::model::ObjectCannedAcl> for ::aws_sdk_s3::types::ObjectCannedAcl {
    fn from(value: crate::model::ObjectCannedAcl) -> Self {
        super::convert::object_canned_acl_to_sdk(&value)
    }
}
impl From<&crate::model::ObjectCannedAcl> for ::aws_sdk_s3::types::ObjectCannedAcl {
    fn from(value: &crate::model::ObjectCannedAcl) -> Self {
        super::convert::object_canned_acl_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ObjectCannedAcl> for crate::model::ObjectCannedAcl {
    fn from(value: ::aws_sdk_s3::types::ObjectCannedAcl) -> Self {
        super::convert::object_canned_acl_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ObjectCannedAcl> for crate::model::ObjectCannedAcl {
    fn from(value: &::aws_sdk_s3::types::ObjectCannedAcl) -> Self {
        super::convert::object_canned_acl_from_sdk(value)
    }
}
impl From<crate::model::ObjectLockLegalHoldStatus>
    for ::aws_sdk_s3::types::ObjectLockLegalHoldStatus
{
    fn from(value: crate::model::ObjectLockLegalHoldStatus) -> Self {
        super::convert::object_lock_legal_hold_status_to_sdk(&value)
    }
}
impl From<&crate::model::ObjectLockLegalHoldStatus>
    for ::aws_sdk_s3::types::ObjectLockLegalHoldStatus
{
    fn from(value: &crate::model::ObjectLockLegalHoldStatus) -> Self {
        super::convert::object_lock_legal_hold_status_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ObjectLockLegalHoldStatus>
    for crate::model::ObjectLockLegalHoldStatus
{
    fn from(value: ::aws_sdk_s3::types::ObjectLockLegalHoldStatus) -> Self {
        super::convert::object_lock_legal_hold_status_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ObjectLockLegalHoldStatus>
    for crate::model::ObjectLockLegalHoldStatus
{
    fn from(value: &::aws_sdk_s3::types::ObjectLockLegalHoldStatus) -> Self {
        super::convert::object_lock_legal_hold_status_from_sdk(value)
    }
}
impl From<crate::model::ObjectLockMode> for ::aws_sdk_s3::types::ObjectLockMode {
    fn from(value: crate::model::ObjectLockMode) -> Self {
        super::convert::object_lock_mode_to_sdk(&value)
    }
}
impl From<&crate::model::ObjectLockMode> for ::aws_sdk_s3::types::ObjectLockMode {
    fn from(value: &crate::model::ObjectLockMode) -> Self {
        super::convert::object_lock_mode_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ObjectLockMode> for crate::model::ObjectLockMode {
    fn from(value: ::aws_sdk_s3::types::ObjectLockMode) -> Self {
        super::convert::object_lock_mode_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ObjectLockMode> for crate::model::ObjectLockMode {
    fn from(value: &::aws_sdk_s3::types::ObjectLockMode) -> Self {
        super::convert::object_lock_mode_from_sdk(value)
    }
}
impl From<crate::model::ObjectStorageClass> for ::aws_sdk_s3::types::ObjectStorageClass {
    fn from(value: crate::model::ObjectStorageClass) -> Self {
        super::convert::object_storage_class_to_sdk(&value)
    }
}
impl From<&crate::model::ObjectStorageClass> for ::aws_sdk_s3::types::ObjectStorageClass {
    fn from(value: &crate::model::ObjectStorageClass) -> Self {
        super::convert::object_storage_class_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ObjectStorageClass> for crate::model::ObjectStorageClass {
    fn from(value: ::aws_sdk_s3::types::ObjectStorageClass) -> Self {
        super::convert::object_storage_class_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ObjectStorageClass> for crate::model::ObjectStorageClass {
    fn from(value: &::aws_sdk_s3::types::ObjectStorageClass) -> Self {
        super::convert::object_storage_class_from_sdk(value)
    }
}
impl From<crate::model::ReplicationStatus> for ::aws_sdk_s3::types::ReplicationStatus {
    fn from(value: crate::model::ReplicationStatus) -> Self {
        super::convert::replication_status_to_sdk(&value)
    }
}
impl From<&crate::model::ReplicationStatus> for ::aws_sdk_s3::types::ReplicationStatus {
    fn from(value: &crate::model::ReplicationStatus) -> Self {
        super::convert::replication_status_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ReplicationStatus> for crate::model::ReplicationStatus {
    fn from(value: ::aws_sdk_s3::types::ReplicationStatus) -> Self {
        super::convert::replication_status_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ReplicationStatus> for crate::model::ReplicationStatus {
    fn from(value: &::aws_sdk_s3::types::ReplicationStatus) -> Self {
        super::convert::replication_status_from_sdk(value)
    }
}
impl From<crate::model::RequestCharged> for ::aws_sdk_s3::types::RequestCharged {
    fn from(value: crate::model::RequestCharged) -> Self {
        super::convert::request_charged_to_sdk(&value)
    }
}
impl From<&crate::model::RequestCharged> for ::aws_sdk_s3::types::RequestCharged {
    fn from(value: &crate::model::RequestCharged) -> Self {
        super::convert::request_charged_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::RequestCharged> for crate::model::RequestCharged {
    fn from(value: ::aws_sdk_s3::types::RequestCharged) -> Self {
        super::convert::request_charged_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::RequestCharged> for crate::model::RequestCharged {
    fn from(value: &::aws_sdk_s3::types::RequestCharged) -> Self {
        super::convert::request_charged_from_sdk(value)
    }
}
impl From<crate::model::RequestPayer> for ::aws_sdk_s3::types::RequestPayer {
    fn from(value: crate::model::RequestPayer) -> Self {
        super::convert::request_payer_to_sdk(&value)
    }
}
impl From<&crate::model::RequestPayer> for ::aws_sdk_s3::types::RequestPayer {
    fn from(value: &crate::model::RequestPayer) -> Self {
        super::convert::request_payer_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::RequestPayer> for crate::model::RequestPayer {
    fn from(value: ::aws_sdk_s3::types::RequestPayer) -> Self {
        super::convert::request_payer_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::RequestPayer> for crate::model::RequestPayer {
    fn from(value: &::aws_sdk_s3::types::RequestPayer) -> Self {
        super::convert::request_payer_from_sdk(value)
    }
}
impl From<crate::model::ServerSideEncryption> for ::aws_sdk_s3::types::ServerSideEncryption {
    fn from(value: crate::model::ServerSideEncryption) -> Self {
        super::convert::server_side_encryption_to_sdk(&value)
    }
}
impl From<&crate::model::ServerSideEncryption> for ::aws_sdk_s3::types::ServerSideEncryption {
    fn from(value: &crate::model::ServerSideEncryption) -> Self {
        super::convert::server_side_encryption_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::ServerSideEncryption> for crate::model::ServerSideEncryption {
    fn from(value: ::aws_sdk_s3::types::ServerSideEncryption) -> Self {
        super::convert::server_side_encryption_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::ServerSideEncryption> for crate::model::ServerSideEncryption {
    fn from(value: &::aws_sdk_s3::types::ServerSideEncryption) -> Self {
        super::convert::server_side_encryption_from_sdk(value)
    }
}
impl From<crate::model::StorageClass> for ::aws_sdk_s3::types::StorageClass {
    fn from(value: crate::model::StorageClass) -> Self {
        super::convert::storage_class_to_sdk(&value)
    }
}
impl From<&crate::model::StorageClass> for ::aws_sdk_s3::types::StorageClass {
    fn from(value: &crate::model::StorageClass) -> Self {
        super::convert::storage_class_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::StorageClass> for crate::model::StorageClass {
    fn from(value: ::aws_sdk_s3::types::StorageClass) -> Self {
        super::convert::storage_class_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::StorageClass> for crate::model::StorageClass {
    fn from(value: &::aws_sdk_s3::types::StorageClass) -> Self {
        super::convert::storage_class_from_sdk(value)
    }
}
impl From<crate::model::Object> for ::aws_sdk_s3::types::Object {
    fn from(value: crate::model::Object) -> Self {
        super::convert::object_to_sdk(&value)
    }
}
impl From<&crate::model::Object> for ::aws_sdk_s3::types::Object {
    fn from(value: &crate::model::Object) -> Self {
        super::convert::object_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::Object> for crate::model::Object {
    fn from(value: ::aws_sdk_s3::types::Object) -> Self {
        super::convert::object_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::Object> for crate::model::Object {
    fn from(value: &::aws_sdk_s3::types::Object) -> Self {
        super::convert::object_from_sdk(value)
    }
}
impl From<crate::model::Owner> for ::aws_sdk_s3::types::Owner {
    fn from(value: crate::model::Owner) -> Self {
        super::convert::owner_to_sdk(&value)
    }
}
impl From<&crate::model::Owner> for ::aws_sdk_s3::types::Owner {
    fn from(value: &crate::model::Owner) -> Self {
        super::convert::owner_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::Owner> for crate::model::Owner {
    fn from(value: ::aws_sdk_s3::types::Owner) -> Self {
        super::convert::owner_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::Owner> for crate::model::Owner {
    fn from(value: &::aws_sdk_s3::types::Owner) -> Self {
        super::convert::owner_from_sdk(value)
    }
}
impl From<crate::model::RestoreStatus> for ::aws_sdk_s3::types::RestoreStatus {
    fn from(value: crate::model::RestoreStatus) -> Self {
        super::convert::restore_status_to_sdk(&value)
    }
}
impl From<&crate::model::RestoreStatus> for ::aws_sdk_s3::types::RestoreStatus {
    fn from(value: &crate::model::RestoreStatus) -> Self {
        super::convert::restore_status_to_sdk(value)
    }
}
impl From<::aws_sdk_s3::types::RestoreStatus> for crate::model::RestoreStatus {
    fn from(value: ::aws_sdk_s3::types::RestoreStatus) -> Self {
        super::convert::restore_status_from_sdk(&value)
    }
}
impl From<&::aws_sdk_s3::types::RestoreStatus> for crate::model::RestoreStatus {
    fn from(value: &::aws_sdk_s3::types::RestoreStatus) -> Self {
        super::convert::restore_status_from_sdk(value)
    }
}
/// Extracts response metadata, dropping the response body without reading it.
impl From<::aws_sdk_s3::operation::get_object::GetObjectOutput> for crate::model::ObjectMetadata {
    fn from(value: ::aws_sdk_s3::operation::get_object::GetObjectOutput) -> Self {
        super::convert::object_metadata_from_get_object(&value)
    }
}
impl From<&::aws_sdk_s3::operation::get_object::GetObjectOutput> for crate::model::ObjectMetadata {
    fn from(value: &::aws_sdk_s3::operation::get_object::GetObjectOutput) -> Self {
        super::convert::object_metadata_from_get_object(value)
    }
}
impl From<::aws_sdk_s3::operation::head_object::HeadObjectOutput> for crate::model::ObjectMetadata {
    fn from(value: ::aws_sdk_s3::operation::head_object::HeadObjectOutput) -> Self {
        super::convert::object_metadata_from_head_object(&value)
    }
}
impl From<&::aws_sdk_s3::operation::head_object::HeadObjectOutput>
    for crate::model::ObjectMetadata
{
    fn from(value: &::aws_sdk_s3::operation::head_object::HeadObjectOutput) -> Self {
        super::convert::object_metadata_from_head_object(value)
    }
}
/// Extracts response metadata, dropping the response body without reading it.
impl From<::aws_sdk_s3::operation::get_object::GetObjectOutput> for crate::model::ChunkMetadata {
    fn from(value: ::aws_sdk_s3::operation::get_object::GetObjectOutput) -> Self {
        super::convert::chunk_metadata_from_get_object(&value)
    }
}
impl From<&::aws_sdk_s3::operation::get_object::GetObjectOutput> for crate::model::ChunkMetadata {
    fn from(value: &::aws_sdk_s3::operation::get_object::GetObjectOutput) -> Self {
        super::convert::chunk_metadata_from_get_object(value)
    }
}
impl From<::aws_sdk_s3::operation::put_object::PutObjectOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(value: ::aws_sdk_s3::operation::put_object::PutObjectOutput) -> Self {
        super::convert::upload_output_from_put_object(&value)
    }
}
impl From<&::aws_sdk_s3::operation::put_object::PutObjectOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(value: &::aws_sdk_s3::operation::put_object::PutObjectOutput) -> Self {
        super::convert::upload_output_from_put_object(value)
    }
}
impl From<::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(
        value: ::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput,
    ) -> Self {
        super::convert::upload_output_from_create_multipart_upload(&value)
    }
}
impl From<&::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(
        value: &::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput,
    ) -> Self {
        super::convert::upload_output_from_create_multipart_upload(value)
    }
}
impl From<::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(
        value: ::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput,
    ) -> Self {
        super::convert::upload_output_from_complete_multipart_upload(&value)
    }
}
impl From<&::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput>
    for crate::model::builders::UploadOutputBuilder
{
    fn from(
        value: &::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput,
    ) -> Self {
        super::convert::upload_output_from_complete_multipart_upload(value)
    }
}
impl crate::model::builders::UploadOutputBuilder {
    /// Updates completion response fields while retaining other transfer values.
    pub fn update_from_complete_mpu(
        self,
        output: &::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput,
    ) -> Self {
        super::convert::update_upload_output_from_complete_multipart_upload(self, output)
    }
}
impl ::aws_sdk_s3::operation::RequestId for crate::model::ObjectMetadata {
    fn request_id(&self) -> Option<&str> {
        crate::model::ObjectMetadata::request_id(self)
    }
}
impl ::aws_sdk_s3::operation::RequestIdExt for crate::model::ObjectMetadata {
    fn extended_request_id(&self) -> Option<&str> {
        crate::model::ObjectMetadata::extended_request_id(self)
    }
}
impl ::aws_sdk_s3::operation::RequestId for crate::model::ChunkMetadata {
    fn request_id(&self) -> Option<&str> {
        crate::model::ChunkMetadata::request_id(self)
    }
}
impl ::aws_sdk_s3::operation::RequestIdExt for crate::model::ChunkMetadata {
    fn extended_request_id(&self) -> Option<&str> {
        crate::model::ChunkMetadata::extended_request_id(self)
    }
}
