// Code generated by s3-tm-model-codegen. DO NOT EDIT.
pub(crate) fn archive_status_to_sdk(
    value: &crate::model::ArchiveStatus,
) -> ::aws_sdk_s3::types::ArchiveStatus {
    ::aws_sdk_s3::types::ArchiveStatus::from(value.as_str())
}
pub(crate) fn archive_status_from_sdk(
    value: &::aws_sdk_s3::types::ArchiveStatus,
) -> crate::model::ArchiveStatus {
    crate::model::ArchiveStatus::from(value.as_str())
}
pub(crate) fn checksum_algorithm_to_sdk(
    value: &crate::model::ChecksumAlgorithm,
) -> ::aws_sdk_s3::types::ChecksumAlgorithm {
    ::aws_sdk_s3::types::ChecksumAlgorithm::from(value.as_str())
}
pub(crate) fn checksum_algorithm_from_sdk(
    value: &::aws_sdk_s3::types::ChecksumAlgorithm,
) -> crate::model::ChecksumAlgorithm {
    crate::model::ChecksumAlgorithm::from(value.as_str())
}
pub(crate) fn checksum_mode_to_sdk(
    value: &crate::model::ChecksumMode,
) -> ::aws_sdk_s3::types::ChecksumMode {
    ::aws_sdk_s3::types::ChecksumMode::from(value.as_str())
}
pub(crate) fn checksum_mode_from_sdk(
    value: &::aws_sdk_s3::types::ChecksumMode,
) -> crate::model::ChecksumMode {
    crate::model::ChecksumMode::from(value.as_str())
}
pub(crate) fn checksum_type_to_sdk(
    value: &crate::model::ChecksumType,
) -> ::aws_sdk_s3::types::ChecksumType {
    ::aws_sdk_s3::types::ChecksumType::from(value.as_str())
}
pub(crate) fn checksum_type_from_sdk(
    value: &::aws_sdk_s3::types::ChecksumType,
) -> crate::model::ChecksumType {
    crate::model::ChecksumType::from(value.as_str())
}
pub(crate) fn object_canned_acl_to_sdk(
    value: &crate::model::ObjectCannedAcl,
) -> ::aws_sdk_s3::types::ObjectCannedAcl {
    ::aws_sdk_s3::types::ObjectCannedAcl::from(value.as_str())
}
pub(crate) fn object_canned_acl_from_sdk(
    value: &::aws_sdk_s3::types::ObjectCannedAcl,
) -> crate::model::ObjectCannedAcl {
    crate::model::ObjectCannedAcl::from(value.as_str())
}
pub(crate) fn object_lock_legal_hold_status_to_sdk(
    value: &crate::model::ObjectLockLegalHoldStatus,
) -> ::aws_sdk_s3::types::ObjectLockLegalHoldStatus {
    ::aws_sdk_s3::types::ObjectLockLegalHoldStatus::from(value.as_str())
}
pub(crate) fn object_lock_legal_hold_status_from_sdk(
    value: &::aws_sdk_s3::types::ObjectLockLegalHoldStatus,
) -> crate::model::ObjectLockLegalHoldStatus {
    crate::model::ObjectLockLegalHoldStatus::from(value.as_str())
}
pub(crate) fn object_lock_mode_to_sdk(
    value: &crate::model::ObjectLockMode,
) -> ::aws_sdk_s3::types::ObjectLockMode {
    ::aws_sdk_s3::types::ObjectLockMode::from(value.as_str())
}
pub(crate) fn object_lock_mode_from_sdk(
    value: &::aws_sdk_s3::types::ObjectLockMode,
) -> crate::model::ObjectLockMode {
    crate::model::ObjectLockMode::from(value.as_str())
}
pub(crate) fn object_storage_class_to_sdk(
    value: &crate::model::ObjectStorageClass,
) -> ::aws_sdk_s3::types::ObjectStorageClass {
    ::aws_sdk_s3::types::ObjectStorageClass::from(value.as_str())
}
pub(crate) fn object_storage_class_from_sdk(
    value: &::aws_sdk_s3::types::ObjectStorageClass,
) -> crate::model::ObjectStorageClass {
    crate::model::ObjectStorageClass::from(value.as_str())
}
pub(crate) fn replication_status_to_sdk(
    value: &crate::model::ReplicationStatus,
) -> ::aws_sdk_s3::types::ReplicationStatus {
    ::aws_sdk_s3::types::ReplicationStatus::from(value.as_str())
}
pub(crate) fn replication_status_from_sdk(
    value: &::aws_sdk_s3::types::ReplicationStatus,
) -> crate::model::ReplicationStatus {
    crate::model::ReplicationStatus::from(value.as_str())
}
pub(crate) fn request_charged_to_sdk(
    value: &crate::model::RequestCharged,
) -> ::aws_sdk_s3::types::RequestCharged {
    ::aws_sdk_s3::types::RequestCharged::from(value.as_str())
}
pub(crate) fn request_charged_from_sdk(
    value: &::aws_sdk_s3::types::RequestCharged,
) -> crate::model::RequestCharged {
    crate::model::RequestCharged::from(value.as_str())
}
pub(crate) fn request_payer_to_sdk(
    value: &crate::model::RequestPayer,
) -> ::aws_sdk_s3::types::RequestPayer {
    ::aws_sdk_s3::types::RequestPayer::from(value.as_str())
}
pub(crate) fn request_payer_from_sdk(
    value: &::aws_sdk_s3::types::RequestPayer,
) -> crate::model::RequestPayer {
    crate::model::RequestPayer::from(value.as_str())
}
pub(crate) fn server_side_encryption_to_sdk(
    value: &crate::model::ServerSideEncryption,
) -> ::aws_sdk_s3::types::ServerSideEncryption {
    ::aws_sdk_s3::types::ServerSideEncryption::from(value.as_str())
}
pub(crate) fn server_side_encryption_from_sdk(
    value: &::aws_sdk_s3::types::ServerSideEncryption,
) -> crate::model::ServerSideEncryption {
    crate::model::ServerSideEncryption::from(value.as_str())
}
pub(crate) fn storage_class_to_sdk(
    value: &crate::model::StorageClass,
) -> ::aws_sdk_s3::types::StorageClass {
    ::aws_sdk_s3::types::StorageClass::from(value.as_str())
}
pub(crate) fn storage_class_from_sdk(
    value: &::aws_sdk_s3::types::StorageClass,
) -> crate::model::StorageClass {
    crate::model::StorageClass::from(value.as_str())
}

pub(crate) fn object_to_sdk(value: &crate::model::Object) -> ::aws_sdk_s3::types::Object {
    let builder = ::aws_sdk_s3::types::Object::builder()
        .set_key(value.key.to_owned())
        .set_last_modified(value.last_modified.to_owned())
        .set_e_tag(value.e_tag.to_owned())
        .set_checksum_algorithm(
            value
                .checksum_algorithm
                .as_ref()
                .map(|value| value.iter().map(checksum_algorithm_to_sdk).collect()),
        )
        .set_checksum_type(value.checksum_type.as_ref().map(checksum_type_to_sdk))
        .set_size(value.size.to_owned())
        .set_storage_class(
            value
                .storage_class
                .as_ref()
                .map(object_storage_class_to_sdk),
        )
        .set_owner(value.owner.as_ref().map(owner_to_sdk))
        .set_restore_status(value.restore_status.as_ref().map(restore_status_to_sdk));
    builder.build()
}
pub(crate) fn object_from_sdk(value: &::aws_sdk_s3::types::Object) -> crate::model::Object {
    let builder = crate::model::Object::builder()
        .set_key(value.key.to_owned())
        .set_last_modified(value.last_modified.to_owned())
        .set_e_tag(value.e_tag.to_owned())
        .set_checksum_algorithm(
            value
                .checksum_algorithm
                .as_ref()
                .map(|value| value.iter().map(checksum_algorithm_from_sdk).collect()),
        )
        .set_checksum_type(value.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_size(value.size.to_owned())
        .set_storage_class(
            value
                .storage_class
                .as_ref()
                .map(object_storage_class_from_sdk),
        )
        .set_owner(value.owner.as_ref().map(owner_from_sdk))
        .set_restore_status(value.restore_status.as_ref().map(restore_status_from_sdk));
    builder.build()
}
pub(crate) fn owner_to_sdk(value: &crate::model::Owner) -> ::aws_sdk_s3::types::Owner {
    let builder = ::aws_sdk_s3::types::Owner::builder()
        .set_display_name(value.display_name.to_owned())
        .set_id(value.id.to_owned());
    builder.build()
}
pub(crate) fn owner_from_sdk(value: &::aws_sdk_s3::types::Owner) -> crate::model::Owner {
    let builder = crate::model::Owner::builder()
        .set_display_name(value.display_name.to_owned())
        .set_id(value.id.to_owned());
    builder.build()
}
pub(crate) fn restore_status_to_sdk(
    value: &crate::model::RestoreStatus,
) -> ::aws_sdk_s3::types::RestoreStatus {
    let builder = ::aws_sdk_s3::types::RestoreStatus::builder()
        .set_is_restore_in_progress(value.is_restore_in_progress.to_owned())
        .set_restore_expiry_date(value.restore_expiry_date.to_owned());
    builder.build()
}
pub(crate) fn restore_status_from_sdk(
    value: &::aws_sdk_s3::types::RestoreStatus,
) -> crate::model::RestoreStatus {
    let builder = crate::model::RestoreStatus::builder()
        .set_is_restore_in_progress(value.is_restore_in_progress.to_owned())
        .set_restore_expiry_date(value.restore_expiry_date.to_owned());
    builder.build()
}

pub(crate) fn copy_upload_input_fields_to_put_object(
    input: &crate::model::UploadInput,
    builder: ::aws_sdk_s3::operation::put_object::builders::PutObjectFluentBuilder,
) -> ::aws_sdk_s3::operation::put_object::builders::PutObjectFluentBuilder {
    builder
        .set_acl(input.acl.as_ref().map(object_canned_acl_to_sdk))
        .set_bucket(input.bucket.to_owned())
        .set_cache_control(input.cache_control.to_owned())
        .set_content_disposition(input.content_disposition.to_owned())
        .set_content_encoding(input.content_encoding.to_owned())
        .set_content_language(input.content_language.to_owned())
        .set_content_md5(input.content_md5.to_owned())
        .set_content_type(input.content_type.to_owned())
        .set_expires(input.expires.to_owned())
        .set_if_match(input.if_match.to_owned())
        .set_if_none_match(input.if_none_match.to_owned())
        .set_grant_full_control(input.grant_full_control.to_owned())
        .set_grant_read(input.grant_read.to_owned())
        .set_grant_read_acp(input.grant_read_acp.to_owned())
        .set_grant_write_acp(input.grant_write_acp.to_owned())
        .set_key(input.key.to_owned())
        .set_metadata(input.metadata.as_ref().map(|value| {
            value
                .iter()
                .map(|(key, item)| (key.clone(), item.to_owned()))
                .collect()
        }))
        .set_server_side_encryption(
            input
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_to_sdk),
        )
        .set_storage_class(input.storage_class.as_ref().map(storage_class_to_sdk))
        .set_website_redirect_location(input.website_redirect_location.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
        .set_ssekms_key_id(input.sse_kms_key_id.to_owned())
        .set_ssekms_encryption_context(input.sse_kms_encryption_context.to_owned())
        .set_bucket_key_enabled(input.bucket_key_enabled.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_tagging(input.tagging.to_owned())
        .set_object_lock_mode(input.object_lock_mode.as_ref().map(object_lock_mode_to_sdk))
        .set_object_lock_retain_until_date(input.object_lock_retain_until_date.to_owned())
        .set_object_lock_legal_hold_status(
            input
                .object_lock_legal_hold_status
                .as_ref()
                .map(object_lock_legal_hold_status_to_sdk),
        )
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
}
pub(crate) fn copy_upload_input_fields_to_create_multipart_upload(
    input: &crate::model::UploadInput,
    builder: ::aws_sdk_s3::operation::create_multipart_upload::builders::CreateMultipartUploadFluentBuilder,
) -> ::aws_sdk_s3::operation::create_multipart_upload::builders::CreateMultipartUploadFluentBuilder
{
    builder
        .set_acl(input.acl.as_ref().map(object_canned_acl_to_sdk))
        .set_bucket(input.bucket.to_owned())
        .set_cache_control(input.cache_control.to_owned())
        .set_content_disposition(input.content_disposition.to_owned())
        .set_content_encoding(input.content_encoding.to_owned())
        .set_content_language(input.content_language.to_owned())
        .set_content_type(input.content_type.to_owned())
        .set_expires(input.expires.to_owned())
        .set_grant_full_control(input.grant_full_control.to_owned())
        .set_grant_read(input.grant_read.to_owned())
        .set_grant_read_acp(input.grant_read_acp.to_owned())
        .set_grant_write_acp(input.grant_write_acp.to_owned())
        .set_key(input.key.to_owned())
        .set_metadata(input.metadata.as_ref().map(|value| {
            value
                .iter()
                .map(|(key, item)| (key.clone(), item.to_owned()))
                .collect()
        }))
        .set_server_side_encryption(
            input
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_to_sdk),
        )
        .set_storage_class(input.storage_class.as_ref().map(storage_class_to_sdk))
        .set_website_redirect_location(input.website_redirect_location.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
        .set_ssekms_key_id(input.sse_kms_key_id.to_owned())
        .set_ssekms_encryption_context(input.sse_kms_encryption_context.to_owned())
        .set_bucket_key_enabled(input.bucket_key_enabled.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_tagging(input.tagging.to_owned())
        .set_object_lock_mode(input.object_lock_mode.as_ref().map(object_lock_mode_to_sdk))
        .set_object_lock_retain_until_date(input.object_lock_retain_until_date.to_owned())
        .set_object_lock_legal_hold_status(
            input
                .object_lock_legal_hold_status
                .as_ref()
                .map(object_lock_legal_hold_status_to_sdk),
        )
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
}
pub(crate) fn copy_upload_input_fields_to_upload_part(
    input: &crate::model::UploadInput,
    builder: ::aws_sdk_s3::operation::upload_part::builders::UploadPartFluentBuilder,
) -> ::aws_sdk_s3::operation::upload_part::builders::UploadPartFluentBuilder {
    builder
        .set_bucket(input.bucket.to_owned())
        .set_key(input.key.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
}
pub(crate) fn copy_upload_input_fields_to_complete_multipart_upload(input: &crate::model::UploadInput, builder: ::aws_sdk_s3::operation::complete_multipart_upload::builders::CompleteMultipartUploadFluentBuilder) -> ::aws_sdk_s3::operation::complete_multipart_upload::builders::CompleteMultipartUploadFluentBuilder{
    builder
        .set_bucket(input.bucket.to_owned())
        .set_key(input.key.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
        .set_if_match(input.if_match.to_owned())
        .set_if_none_match(input.if_none_match.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
}
pub(crate) fn copy_upload_input_fields_to_abort_multipart_upload(
    input: &crate::model::UploadInput,
    builder: ::aws_sdk_s3::operation::abort_multipart_upload::builders::AbortMultipartUploadFluentBuilder,
) -> ::aws_sdk_s3::operation::abort_multipart_upload::builders::AbortMultipartUploadFluentBuilder {
    builder
        .set_bucket(input.bucket.to_owned())
        .set_key(input.key.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
}
pub(crate) fn copy_download_input_fields_to_get_object(
    input: &crate::model::DownloadInput,
    builder: ::aws_sdk_s3::operation::get_object::builders::GetObjectFluentBuilder,
) -> ::aws_sdk_s3::operation::get_object::builders::GetObjectFluentBuilder {
    builder
        .set_bucket(input.bucket.to_owned())
        .set_if_match(input.if_match.to_owned())
        .set_if_modified_since(input.if_modified_since.to_owned())
        .set_if_none_match(input.if_none_match.to_owned())
        .set_if_unmodified_since(input.if_unmodified_since.to_owned())
        .set_key(input.key.to_owned())
        .set_range(input.range.to_owned())
        .set_response_cache_control(input.response_cache_control.to_owned())
        .set_response_content_disposition(input.response_content_disposition.to_owned())
        .set_response_content_encoding(input.response_content_encoding.to_owned())
        .set_response_content_language(input.response_content_language.to_owned())
        .set_response_content_type(input.response_content_type.to_owned())
        .set_response_expires(input.response_expires.to_owned())
        .set_version_id(input.version_id.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
        .set_checksum_mode(input.checksum_mode.as_ref().map(checksum_mode_to_sdk))
}
pub(crate) fn copy_download_input_fields_to_head_object(
    input: &crate::model::DownloadInput,
    builder: ::aws_sdk_s3::operation::head_object::builders::HeadObjectFluentBuilder,
) -> ::aws_sdk_s3::operation::head_object::builders::HeadObjectFluentBuilder {
    builder
        .set_bucket(input.bucket.to_owned())
        .set_if_match(input.if_match.to_owned())
        .set_if_modified_since(input.if_modified_since.to_owned())
        .set_if_none_match(input.if_none_match.to_owned())
        .set_if_unmodified_since(input.if_unmodified_since.to_owned())
        .set_key(input.key.to_owned())
        .set_range(input.range.to_owned())
        .set_response_cache_control(input.response_cache_control.to_owned())
        .set_response_content_disposition(input.response_content_disposition.to_owned())
        .set_response_content_encoding(input.response_content_encoding.to_owned())
        .set_response_content_language(input.response_content_language.to_owned())
        .set_response_content_type(input.response_content_type.to_owned())
        .set_response_expires(input.response_expires.to_owned())
        .set_version_id(input.version_id.to_owned())
        .set_sse_customer_algorithm(input.sse_customer_algorithm.to_owned())
        .set_sse_customer_key(input.sse_customer_key.to_owned())
        .set_sse_customer_key_md5(input.sse_customer_key_md5.to_owned())
        .set_request_payer(input.request_payer.as_ref().map(request_payer_to_sdk))
        .set_expected_bucket_owner(input.expected_bucket_owner.to_owned())
        .set_checksum_mode(input.checksum_mode.as_ref().map(checksum_mode_to_sdk))
}

use ::aws_sdk_s3::operation::{RequestId, RequestIdExt};
pub(crate) fn object_metadata_from_get_object(
    output: &::aws_sdk_s3::operation::get_object::GetObjectOutput,
) -> crate::model::ObjectMetadata {
    let builder = crate::model::ObjectMetadata::builder();
    builder
        .set_delete_marker(output.delete_marker.to_owned())
        .set_accept_ranges(output.accept_ranges.to_owned())
        .set_expiration(output.expiration.to_owned())
        .set_restore(output.restore.to_owned())
        .set_last_modified(output.last_modified.to_owned())
        .set_content_length(output.content_length.to_owned())
        .set_e_tag(output.e_tag.to_owned())
        .set_checksum_crc32(output.checksum_crc32.to_owned())
        .set_checksum_crc32_c(output.checksum_crc32_c.to_owned())
        .set_checksum_crc64_nvme(output.checksum_crc64_nvme.to_owned())
        .set_checksum_sha1(output.checksum_sha1.to_owned())
        .set_checksum_sha256(output.checksum_sha256.to_owned())
        .set_checksum_sha512(output.checksum_sha512.to_owned())
        .set_checksum_md5(output.checksum_md5.to_owned())
        .set_checksum_xxhash64(output.checksum_xxhash64.to_owned())
        .set_checksum_xxhash3(output.checksum_xxhash3.to_owned())
        .set_checksum_xxhash128(output.checksum_xxhash128.to_owned())
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_missing_meta(output.missing_meta.to_owned())
        .set_version_id(output.version_id.to_owned())
        .set_cache_control(output.cache_control.to_owned())
        .set_content_disposition(output.content_disposition.to_owned())
        .set_content_encoding(output.content_encoding.to_owned())
        .set_content_language(output.content_language.to_owned())
        .set_content_range(output.content_range.to_owned())
        .set_content_type(output.content_type.to_owned())
        .set_expires_string(output.expires_string.to_owned())
        .set_website_redirect_location(output.website_redirect_location.to_owned())
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_metadata(output.metadata.as_ref().map(|value| {
            value
                .iter()
                .map(|(key, item)| (key.clone(), item.to_owned()))
                .collect()
        }))
        .set_sse_customer_algorithm(output.sse_customer_algorithm.to_owned())
        .set_sse_customer_key_md5(output.sse_customer_key_md5.to_owned())
        .set_ssekms_key_id(output.ssekms_key_id.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_storage_class(output.storage_class.as_ref().map(storage_class_from_sdk))
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
        .set_replication_status(
            output
                .replication_status
                .as_ref()
                .map(replication_status_from_sdk),
        )
        .set_parts_count(output.parts_count.to_owned())
        .set_tag_count(output.tag_count.to_owned())
        .set_object_lock_mode(
            output
                .object_lock_mode
                .as_ref()
                .map(object_lock_mode_from_sdk),
        )
        .set_object_lock_retain_until_date(output.object_lock_retain_until_date.to_owned())
        .set_object_lock_legal_hold_status(
            output
                .object_lock_legal_hold_status
                .as_ref()
                .map(object_lock_legal_hold_status_from_sdk),
        )
        .set_request_id(output.request_id().map(str::to_owned))
        .set_extended_request_id(output.extended_request_id().map(str::to_owned))
        .build()
}
pub(crate) fn object_metadata_from_head_object(
    output: &::aws_sdk_s3::operation::head_object::HeadObjectOutput,
) -> crate::model::ObjectMetadata {
    let builder = crate::model::ObjectMetadata::builder();
    builder
        .set_delete_marker(output.delete_marker.to_owned())
        .set_accept_ranges(output.accept_ranges.to_owned())
        .set_expiration(output.expiration.to_owned())
        .set_restore(output.restore.to_owned())
        .set_archive_status(output.archive_status.as_ref().map(archive_status_from_sdk))
        .set_last_modified(output.last_modified.to_owned())
        .set_content_length(output.content_length.to_owned())
        .set_checksum_crc32(output.checksum_crc32.to_owned())
        .set_checksum_crc32_c(output.checksum_crc32_c.to_owned())
        .set_checksum_crc64_nvme(output.checksum_crc64_nvme.to_owned())
        .set_checksum_sha1(output.checksum_sha1.to_owned())
        .set_checksum_sha256(output.checksum_sha256.to_owned())
        .set_checksum_sha512(output.checksum_sha512.to_owned())
        .set_checksum_md5(output.checksum_md5.to_owned())
        .set_checksum_xxhash64(output.checksum_xxhash64.to_owned())
        .set_checksum_xxhash3(output.checksum_xxhash3.to_owned())
        .set_checksum_xxhash128(output.checksum_xxhash128.to_owned())
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_e_tag(output.e_tag.to_owned())
        .set_missing_meta(output.missing_meta.to_owned())
        .set_version_id(output.version_id.to_owned())
        .set_cache_control(output.cache_control.to_owned())
        .set_content_disposition(output.content_disposition.to_owned())
        .set_content_encoding(output.content_encoding.to_owned())
        .set_content_language(output.content_language.to_owned())
        .set_content_type(output.content_type.to_owned())
        .set_content_range(output.content_range.to_owned())
        .set_expires_string(output.expires_string.to_owned())
        .set_website_redirect_location(output.website_redirect_location.to_owned())
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_metadata(output.metadata.as_ref().map(|value| {
            value
                .iter()
                .map(|(key, item)| (key.clone(), item.to_owned()))
                .collect()
        }))
        .set_sse_customer_algorithm(output.sse_customer_algorithm.to_owned())
        .set_sse_customer_key_md5(output.sse_customer_key_md5.to_owned())
        .set_ssekms_key_id(output.ssekms_key_id.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_storage_class(output.storage_class.as_ref().map(storage_class_from_sdk))
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
        .set_replication_status(
            output
                .replication_status
                .as_ref()
                .map(replication_status_from_sdk),
        )
        .set_parts_count(output.parts_count.to_owned())
        .set_tag_count(output.tag_count.to_owned())
        .set_object_lock_mode(
            output
                .object_lock_mode
                .as_ref()
                .map(object_lock_mode_from_sdk),
        )
        .set_object_lock_retain_until_date(output.object_lock_retain_until_date.to_owned())
        .set_object_lock_legal_hold_status(
            output
                .object_lock_legal_hold_status
                .as_ref()
                .map(object_lock_legal_hold_status_from_sdk),
        )
        .set_request_id(output.request_id().map(str::to_owned))
        .set_extended_request_id(output.extended_request_id().map(str::to_owned))
        .build()
}
pub(crate) fn chunk_metadata_from_get_object(
    output: &::aws_sdk_s3::operation::get_object::GetObjectOutput,
) -> crate::model::ChunkMetadata {
    let builder = crate::model::ChunkMetadata::builder();
    builder
        .set_delete_marker(output.delete_marker.to_owned())
        .set_accept_ranges(output.accept_ranges.to_owned())
        .set_expiration(output.expiration.to_owned())
        .set_restore(output.restore.to_owned())
        .set_last_modified(output.last_modified.to_owned())
        .set_content_length(output.content_length.to_owned())
        .set_e_tag(output.e_tag.to_owned())
        .set_checksum_crc32(output.checksum_crc32.to_owned())
        .set_checksum_crc32_c(output.checksum_crc32_c.to_owned())
        .set_checksum_crc64_nvme(output.checksum_crc64_nvme.to_owned())
        .set_checksum_sha1(output.checksum_sha1.to_owned())
        .set_checksum_sha256(output.checksum_sha256.to_owned())
        .set_checksum_sha512(output.checksum_sha512.to_owned())
        .set_checksum_md5(output.checksum_md5.to_owned())
        .set_checksum_xxhash64(output.checksum_xxhash64.to_owned())
        .set_checksum_xxhash3(output.checksum_xxhash3.to_owned())
        .set_checksum_xxhash128(output.checksum_xxhash128.to_owned())
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_missing_meta(output.missing_meta.to_owned())
        .set_version_id(output.version_id.to_owned())
        .set_cache_control(output.cache_control.to_owned())
        .set_content_disposition(output.content_disposition.to_owned())
        .set_content_encoding(output.content_encoding.to_owned())
        .set_content_language(output.content_language.to_owned())
        .set_content_range(output.content_range.to_owned())
        .set_content_type(output.content_type.to_owned())
        .set_expires_string(output.expires_string.to_owned())
        .set_website_redirect_location(output.website_redirect_location.to_owned())
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_metadata(output.metadata.as_ref().map(|value| {
            value
                .iter()
                .map(|(key, item)| (key.clone(), item.to_owned()))
                .collect()
        }))
        .set_sse_customer_algorithm(output.sse_customer_algorithm.to_owned())
        .set_sse_customer_key_md5(output.sse_customer_key_md5.to_owned())
        .set_ssekms_key_id(output.ssekms_key_id.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_storage_class(output.storage_class.as_ref().map(storage_class_from_sdk))
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
        .set_replication_status(
            output
                .replication_status
                .as_ref()
                .map(replication_status_from_sdk),
        )
        .set_parts_count(output.parts_count.to_owned())
        .set_tag_count(output.tag_count.to_owned())
        .set_object_lock_mode(
            output
                .object_lock_mode
                .as_ref()
                .map(object_lock_mode_from_sdk),
        )
        .set_object_lock_retain_until_date(output.object_lock_retain_until_date.to_owned())
        .set_object_lock_legal_hold_status(
            output
                .object_lock_legal_hold_status
                .as_ref()
                .map(object_lock_legal_hold_status_from_sdk),
        )
        .set_request_id(output.request_id().map(str::to_owned))
        .set_extended_request_id(output.extended_request_id().map(str::to_owned))
        .build()
}
pub(crate) fn upload_output_from_put_object(
    output: &::aws_sdk_s3::operation::put_object::PutObjectOutput,
) -> crate::model::builders::UploadOutputBuilder {
    update_upload_output_from_put_object(crate::model::UploadOutput::builder(), output)
}
pub(crate) fn update_upload_output_from_put_object(
    builder: crate::model::builders::UploadOutputBuilder,
    output: &::aws_sdk_s3::operation::put_object::PutObjectOutput,
) -> crate::model::builders::UploadOutputBuilder {
    builder
        .set_expiration(output.expiration.to_owned())
        .set_e_tag(output.e_tag.to_owned())
        .set_checksum_crc32(output.checksum_crc32.to_owned())
        .set_checksum_crc32_c(output.checksum_crc32_c.to_owned())
        .set_checksum_crc64_nvme(output.checksum_crc64_nvme.to_owned())
        .set_checksum_sha1(output.checksum_sha1.to_owned())
        .set_checksum_sha256(output.checksum_sha256.to_owned())
        .set_checksum_sha512(output.checksum_sha512.to_owned())
        .set_checksum_md5(output.checksum_md5.to_owned())
        .set_checksum_xxhash64(output.checksum_xxhash64.to_owned())
        .set_checksum_xxhash3(output.checksum_xxhash3.to_owned())
        .set_checksum_xxhash128(output.checksum_xxhash128.to_owned())
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_version_id(output.version_id.to_owned())
        .set_sse_customer_algorithm(output.sse_customer_algorithm.to_owned())
        .set_sse_customer_key_md5(output.sse_customer_key_md5.to_owned())
        .set_sse_kms_key_id(output.ssekms_key_id.to_owned())
        .set_sse_kms_encryption_context(output.ssekms_encryption_context.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_size(output.size.to_owned())
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
}
pub(crate) fn upload_output_from_create_multipart_upload(
    output: &::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput,
) -> crate::model::builders::UploadOutputBuilder {
    update_upload_output_from_create_multipart_upload(crate::model::UploadOutput::builder(), output)
}
pub(crate) fn update_upload_output_from_create_multipart_upload(
    builder: crate::model::builders::UploadOutputBuilder,
    output: &::aws_sdk_s3::operation::create_multipart_upload::CreateMultipartUploadOutput,
) -> crate::model::builders::UploadOutputBuilder {
    builder
        .set_abort_date(output.abort_date.to_owned())
        .set_abort_rule_id(output.abort_rule_id.to_owned())
        .set_bucket(output.bucket.to_owned())
        .set_key(output.key.to_owned())
        .set_upload_id(output.upload_id.to_owned())
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_sse_customer_algorithm(output.sse_customer_algorithm.to_owned())
        .set_sse_customer_key_md5(output.sse_customer_key_md5.to_owned())
        .set_sse_kms_key_id(output.ssekms_key_id.to_owned())
        .set_sse_kms_encryption_context(output.ssekms_encryption_context.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
        .set_checksum_algorithm(
            output
                .checksum_algorithm
                .as_ref()
                .map(checksum_algorithm_from_sdk),
        )
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
}
pub(crate) fn upload_output_from_complete_multipart_upload(
    output: &::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput,
) -> crate::model::builders::UploadOutputBuilder {
    update_upload_output_from_complete_multipart_upload(
        crate::model::UploadOutput::builder(),
        output,
    )
}
pub(crate) fn update_upload_output_from_complete_multipart_upload(
    builder: crate::model::builders::UploadOutputBuilder,
    output: &::aws_sdk_s3::operation::complete_multipart_upload::CompleteMultipartUploadOutput,
) -> crate::model::builders::UploadOutputBuilder {
    builder
        .set_location(output.location.to_owned())
        .set_bucket(output.bucket.to_owned())
        .set_key(output.key.to_owned())
        .set_expiration(output.expiration.to_owned())
        .set_e_tag(output.e_tag.to_owned())
        .set_checksum_crc32(output.checksum_crc32.to_owned())
        .set_checksum_crc32_c(output.checksum_crc32_c.to_owned())
        .set_checksum_crc64_nvme(output.checksum_crc64_nvme.to_owned())
        .set_checksum_sha1(output.checksum_sha1.to_owned())
        .set_checksum_sha256(output.checksum_sha256.to_owned())
        .set_checksum_sha512(output.checksum_sha512.to_owned())
        .set_checksum_md5(output.checksum_md5.to_owned())
        .set_checksum_xxhash64(output.checksum_xxhash64.to_owned())
        .set_checksum_xxhash3(output.checksum_xxhash3.to_owned())
        .set_checksum_xxhash128(output.checksum_xxhash128.to_owned())
        .set_checksum_type(output.checksum_type.as_ref().map(checksum_type_from_sdk))
        .set_server_side_encryption(
            output
                .server_side_encryption
                .as_ref()
                .map(server_side_encryption_from_sdk),
        )
        .set_version_id(output.version_id.to_owned())
        .set_sse_kms_key_id(output.ssekms_key_id.to_owned())
        .set_bucket_key_enabled(output.bucket_key_enabled.to_owned())
        .set_request_charged(
            output
                .request_charged
                .as_ref()
                .map(request_charged_from_sdk),
        )
}
